### ISSUE TITLE
Mixing ui.download_button() with `render.downlaod` breaks `render.download`

### ISSUE THREAD

**Issue by gshotwell** [posit-dev/py-shiny#1002]
In Express if you define a download button with a render.download decorator the second button fails to work.  Is there a reason to have `ui.download_button` in Express at this point?

```
ui.download_button("dl1", "Download")

@render.download(label="Download text", filename="hello.txt")
def dl1():
    yield "Hello, world!\n"
```

**Comment by wch** [comment]
This is the same issue as with all the other output functions, for example:

```
ui.output_text("txt")

@render.text()
def txt():
    return "Hi"
```

Once we update the shiny.js assets to get the latest from rstudio/shiny, that will bring in the error console, which will display output name conflicts.
