### ISSUE TITLE
Website: "Function Reference" page for `ui.tags`

### ISSUE THREAD

**Issue by youngroklee-ml** [posit-dev/py-shiny#1005]
In the following links, the list of function description goes only up to "iframe", and many of the description shows just "Create a".
https://shiny.posit.co/py/api/ui.tags.html

![image](https://github.com/posit-dev/py-shiny/assets/30917347/fa5382d2-a4b3-48f1-af74-303bb1c799cb)

**Comment by youngroklee-ml** [comment]
I did not know that there is a separate repository for website. I resubmitted this issue to py-shiny-site repository. https://github.com/posit-dev/py-shiny-site/issues/67#issue-2080879087

**Comment by schloerke** [comment]
Thank you! (closing here)
