### ISSUE TITLE
Updating express inputs leads to an error

### ISSUE THREAD

**Issue by cpsievert** [posit-dev/py-shiny#1034]
Consider the following app, which from a user perspective is functional, but does generate an error (since the 1st time it runs a session hasn't been established):

```python
from shiny import reactive
from shiny.express import ui

ui.input_slider("n", "N", 1, 100, 50)

@reactive.effect
def _():
    ui.update_slider("n", value=10)
```

```python
Traceback (most recent call last):
  File "/Users/cpsievert/github/py-shiny/shiny/reactive/_reactives.py", line 573, in _run
    await self._fn()
  File "/Users/cpsievert/github/py-shiny/shiny/_utils.py", line 243, in fn_async
    return fn(*args, **kwargs)
  File "/Users/cpsievert/github/py-shiny/sandbox/app.py", line 8, in _
    ui.update_slider("n", value=10)
  File "/Users/cpsievert/github/py-shiny/shiny/ui/_input_update.py", line 780, in update_slider
    session = require_active_session(session)
  File "/Users/cpsievert/github/py-shiny/shiny/session/_utils.py", line 127, in require_active_session
    raise RuntimeError(
RuntimeError: update_slider() must be called from within an active Shiny session.
/Users/cpsievert/github/py-shiny/shiny/reactive/_reactives.py:555: ReactiveWarning: Error in Effect: update_slider() must be called from within an active Shiny session.
  await self._run()
```

**Comment by wch** [comment]
This is a real issue, but I will note that in practice, most uses will only call the `update_*` function after something else has happened. For example, it might use `reactive.event`. The example below will not throw an error:

```py
from shiny import reactive
from shiny.express import input, ui

ui.input_slider("m", "M", 1, 100, 10)
ui.input_slider("n", "N", 1, 100, 50)


@reactive.effect
@reactive.event(input.m)
def _():
    ui.update_slider("n", value=input.m())
```

**Comment by cpsievert** [comment]
That's true, but it's also not great that if you try use any `session` methods, you get an unhelpful error. For example:

```python
from shiny import reactive
from shiny.express import session

@reactive.effect
async def _():
    await session.send_custom_message("msg", {})
```

```python
Error in Effect: '_MockSession' object has no attribute 'send_custom_message'
```

You also can't avoid the error with something like `if session:` since the mock session object is truthy

**Comment by jcheng5** [comment]
I think it's extremely important that `@reactive.effect` NOT run at all if it's created during the UI-generating phase of Express. We could run the UI generating pass with a MockSession in place and `.close()` it as soon as the UI returns, which would auto-destroy any reactive effects.

**Comment by jcheng5** [comment]
I see now that MockSession doesn't have `.on_ended`, it would need that too.

**Comment by wch** [comment]
Just to elaborate a bit on what @jcheng5 said about it being important that `effect`s not run at all: I think the specific issue with `session` stuff being accessed is a manifestation of a more general issue, which is that a copy of these `effect`s are created outside of the session, and they will try to execute, which the user probably will not expect.

**Comment by wch** [comment]
A problem with calling `.close()` is that it's `async`, which means that the caller, `wrap_express_app`, would also need to be `async` -- but that won't work because that function is called when you simply access the `shiny.express.app.xxx`, via a `__getattr__` method, and that can't be `async`.

So I think we may need to change `@reactive.effect` so that it simply no-ops when running in the UI-generating phase.
