### ISSUE TITLE
release with starlette pinned below 0.35

### ISSUE THREAD

**Issue by aronatkins** [posit-dev/py-shiny#1050]
Issue a release containing the change in https://github.com/posit-dev/py-shiny/pull/1009

This avoids a problem when Shiny applications are published to Connect, caused by changes to `root_path` in starlette 0.35.0.

**Comment by gshotwell** [comment]
Oh sorry this was my mistake, I didn't realize that the pin had already been merged. I'm going to close this since it'll go out in 0.7 which should be very soon.
