### ISSUE TITLE
Reactive functions in Express can't modify their parent scope

### ISSUE THREAD

**Issue by cpsievert** [posit-dev/py-shiny#1090]
[For example](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJM6cKITIcAbnAA6Eeo1aduGOAA9Uoli179BwrqgCuZPE2Md58yxiOmA+uMmkHAI1NlSACllg3ZBB+5n4ACtq68H4AlNYQEIQANhyEANYsiLzkTAC8TAAMcQACos7ScGo0NHAS8iViEuVqMuTe9mQYARCxEAAmcDRMDt7RiPJME0wQpInEhFCJU0kp6eOTCclpugDUeQCMaxNaXGTeNH4AQp6kTMtpcL1MIBsrLAC+TJLwLDHyYG8AXSAA)

**Comment by jcheng5** [comment]
I think that’s correct behavior, doesn’t that “nonlocal” need to be “global”?

**Comment by jcheng5** [comment]
Whereas it would be nonlocal if there was another function between the reactive and the top level, and the variable was defined there

**Comment by cpsievert** [comment]
Oh, duh, yea, I just was translating from a Core app and didn't think it through :)

**Comment by wch** [comment]
In the future, can you include the code in the issue? This will make it easier for readers to see the example (and will probably be more reliable than opening shinylive.io).
