### ISSUE TITLE
static_assets doesnt seem to work

### ISSUE THREAD

**Issue by corey-dawson** [posit-dev/py-shiny#1122]
When including the static assets argument in App(), a volume should be added to the path. The documentation states a directory gets mounted at the root, however, I have seen other recommendations showing if the static asset path is a directory, you can reference the files directly.. Additionally, the documentation on python shiny states the volume is mounted to root as a directory. I am not seeing any directory getting mounted in root and am unable to refence the files directly.

Documentation on python shiny for static_assets within App() is very poor and should be improved

Folder Structure:

```
app:
   | app.py
   | resources
        | tst.png
```

# Example code
results in 'no such file or directory'. printing out root directly, no directory named "resources" was mounted to root

```python
from pathlib import Path
from shiny import App, render, ui
from shiny.types import ImgData
import os

app_ui = ui.page_fluid(
    ui.output_image("image")
)

def server(input, output, session):

    @render.image
    def image():
        print(os.listdir("/"))
        img: ImgData = {"src": str("/resources/tst.png"), "width": "100px"}
        return img


resource_dir = Path(__file__).parent / "resources"
app = App(app_ui, server, static_assets=resource_dir)
```

# Second test: updating query image directly (Ideal)
update image path to the file name. results in 'no such file or directory'. This seems the ideal to me

```python
img: ImgData = {"src": str("tst.png"), "width": "100px"}
```

# what does work (undesirable)
this obviously works without using static asssets. However, I want to call the files within 'resources' directly [aka tst.png]

```python
from pathlib import Path
from shiny import App, render, ui
from shiny.types import ImgData
import os

app_ui = ui.page_fluid(
    ui.output_image("image")
)

def server(input, output, session):

    @render.image
    def image():
        resource_dir = Path(__file__).parent
        img_path =  resource_dir.joinpath("resources/tst.png")
        img: ImgData = {"src": str(img_path), "width": "100px"}
        return img

app = App(app_ui, server)
```

**Comment by gadenbuie** [comment]
Hi @corey-dawson, thanks for the question and the reproducible example. In Shiny, you have basically two options for adding images to the user interface:

1. `@render.image` with `ui.output_image()`
2. Or `@render.ui` that returns a `ui.tags.img()` image tag, paired with `ui.output_ui()`.

You could think of these as server-side images (`@render.image`) or client-side images (`ui.tags.img()`). With server-side images, the Shiny server finds the file on the server, reads the file and then sends the image file contents to the client as base64-encoded data. In this scenario, the file path is local and relative to the working directory of the Python process serving the Shiny app.

This is the approach used in the following snippet:

```python
    @render.image
    def image_server():
        return {"src": img_file, "width": "200px"}
```

Here `img_file` points to the file `resources/cat.jpg` adjacent to the app file on the server, but `@render.image` will actually read the contents of the file and send it to the client. On the client side, the HTML will look something like

```html
<img src="data:image/jpeg;base64,/9j/4AAQSkZ..." width="200px">
```

On the other hand, when you use `ui.tags.img(src="/path/to/image.jpg")`, the file is found and read client-side by the browser at `https://<your-server>.com/path/to/image.jpg`. In this set up, you need to use `static_assets` to tell Shiny which directories should be served and their mount point. The file itself isn't sent across the wire directly, instead the web server will provide the file upon request, allowing the HTML in your UI to point to the served file's location:

```python
def server(input, output, session):
    @render.ui
    def image_client():
        return ui.tags.img(src="/images/cat.jpg", width="200px")


app = App(app_ui, server, static_assets={"/images": resource_dir})
```

In the snippet above, we told Shiny to serve `resource_dir` at `/images` and then we referred to the image at the mount point in `src="/images/cat.jpg`. The file isn't sent directly over the wire; the HTML for this UI will look like this

```html
<img src="/images/cat.jpg" width="200px">
```

and the browser will request `/images/tst.jpeg`, which will be served by starlette. In this client-side set up, you can either put `ui.tags.img()` in the `app_ui` directly, or if you need to pick from a set of images you can return the `ui.tags.img()` from a `@render.ui` server function.

Which approach you want to use depends a lot on your use case, but in general:

1. If you're creating the images on the fly, use `@render.image`.
2. If you have a folder of preset static images, use `static_assets` with `ui.tags.img()` and `@render.ui`.

Here's a full app based on your example that demonstrates both approaches.

```python
import os
from pathlib import Path

import requests

from shiny import App, render, ui
from shiny.types import ImgData

resource_dir = Path(__file__).parent / "resources"
img_file = resource_dir / "cat.jpg"

if not os.path.exists(resource_dir):
    os.makedirs(resource_dir)

if not os.path.exists(img_file):
    # download an image from placekitten
    resp = requests.get("https://placekitten.com/200/200")
    with open(img_file, "wb") as f:
        f.write(resp.content)

app_ui = ui.page_fluid(
    ui.output_image("image_server", width="200px", height="200px"),
    ui.output_ui("image_client"),
)


def server(input, output, session):
    @render.image
    def image_server():
        return {"src": img_file, "width": "200px"}

    @render.ui
    def image_client():
        return ui.tags.img(src="/images/cat.jpg", width="200px")


app = App(app_ui, server, static_assets={"images": resource_dir})
```

**Comment by corey-dawson** [comment]
@gadenbuie Thanks for the sample, but I'm still confused on what the static_assets argument does for App()? if it doesn't add a directory to the path, allowing the app to call the file by the file name instead of using a path, what is its purpose? Is the functionality of having a folder [resource or bin or www folder (www folder in R Shiny)] that is by default is in the Apps paths possible? In R Shiny, one could just put an image in www folder in R shiny and call "cat.jpg" instead using the path "www/cat.jpg"

**Comment by gadenbuie** [comment]
@corey-dawson you can think of `static_assets` as the Python equivalent of `shiny::addResourcePath()` in R. When `static_assets` is passed a string value, that value is mounted at `/`, but AFAIK Shiny for Python doesn't automatically mount the `www/` directory.

In other words, you could store `cat.jpg` in `www/` next to your application, set `static_assets="www"`, and then call `ui.tags.img(src="cat.jpg")`.

**Comment by corey-dawson** [comment]
@gadenbuie Thanks for the clarification. I was able to get static_assets to work. In fact, getting static_assets to worked fixed another issue I had put in about rendering a pdf using ui.tags.iframe(), which doesnt seem to work without setting static_assets. Will close this issue. Just on thing worth noting, The stattic assets requires an absolute path:

```python
dir = Path(os.path.abspath('')).resolve()
resource_path = dir.joinpath("resources")
app = App(app_ui, server, static_assets=resource_path)
```
