### ISSUE TITLE
Feature request: Maximum number of inputs for `input_selectize` and `input_checkbox`

### ISSUE THREAD

**Issue by ME-researchgroup** [posit-dev/py-shiny#1127]
Hi!

I was wondering if it would be possible to add functionality to limit the number of selections a user can make for `input_selectize` and `input_checkbox` (and perhaps other widgets?).

I know the [shinyWidgets R package](https://dreamrs.github.io/shinyWidgets/reference/pickerInput.html) introduces some nice support for this, where options grey-out when the maximum number of selections are reached and a message can be displayed, e.g:

```R
pickerInput("picker",
            "Select some options!",
            choices = list("Option1", "Option2", "Option3"),
            multiple = TRUE,
            options =  list(
              "max-options" = 2,
              "max-options-text" = "Don't select more than two, though!"
            ))
```

**Comment by cpsievert** [comment]
[This is possible](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbDOAD1R04LFkw4xUxOmSYBXDgB0IS+Ri6pZZAPos4AGziEyHAF5wAFEqbWmCyHby2wAYSgQmpPdiaE2xYrpMAEwOTMB2AIKhdgBC0S52ALp4VjbEqMakLAC8IHYwUHwAkhQwLHaIwQC+SgCUYFWJQA) with `input_selectize()` via the `maxItems` option that selectize.js provides:

```python
from shiny.express import ui

ui.input_selectize(
    "n", "Can only choose 2", ["A", "B", "C"],
    options={"maxItems": 2}
)
```
