### ISSUE TITLE
R or Python

### ISSUE THREAD

**Issue by WAN-f12** [posit-dev/py-shiny#1210]
HI,
Thank you very much for developing a very useful tool. I want to know whether it is better to use R language or python when using shiny to build web programs such as websites, I need to consider the speed, concurrency and other reasons. Second, what are the advantages of using a networking framework like django?
Looking forward to your reply

**Comment by cpsievert** [comment]
Hi @WAN-f12, this would be a great question to ask on our discord https://discord.com/invite/yMGCamUMnS.

I'll be closing this issue since we use this tracker to manage bug reports and feature requests
