### ISSUE TITLE
Shiny Express rsconnect issues

### ISSUE THREAD

**Issue by gshotwell** [posit-dev/py-shiny#1232]
We discovered two issues with Shiny Express and rsconnect:

1) Currently it's really important that Express users upgrade their version of `rsconnect-python` but if they forget to do  that they get kind of a weird error (the app deploys successfully and they get a runtime error when it starts up). It would be good if there were a check when a user was running their express app to see if the version of rsconnect-python were correct. So check if the user has rsconnect-python installed, and error if it's too old to deploy Express apps. 

2) It doesn't look like `rsconnect write-manifest shiny` is detecting express apps. This is an important feature because it powers Connect git-backed deployment.

**Comment by gadenbuie** [comment]
Looks like there's an open issue in rsconnect-python for the `rsconnect write-manifest` issue: https://github.com/rstudio/rsconnect-python/issues/540

**Comment by wch** [comment]
These have been fixed by #1233 and https://github.com/rstudio/rsconnect-python/pull/558.
