### ISSUE TITLE
Updates when python min version is 3.9

### ISSUE THREAD

**Issue by schloerke** [posit-dev/py-shiny#1237]

**Comment by wch** [comment]
Just curious: why does this Python 3.9?

**Comment by schloerke** [comment]
When inheriting from a class that has a ParamSpec, in Python >= 3.9 the paramspec can be defined as `[]`. In python 3.8, it does not understand it and raises. You can pass in a `P` paramspec, but for the case of `AsycnValueFn`, the ParamSpec should be empty and I couldn't find a way to define it as empty.

**Comment by schloerke** [comment]
Closing as it will not be utilized
