### ISSUE TITLE
Output_data_frame scrollbar jitter (switches classes quickly)

### ISSUE THREAD

**Issue by corey-dawson** [posit-dev/py-shiny#1247]
Hard to replicate, however, I am seeing an issue with render.DataGrid and output_data_frame functions where the output table is jittering between classes "shiny-data-grid shiny-data-grid-grid" and "shiny-data-grid shiny-data-grid-grid scrolling". The scroll bar is basically turning on and off really quickly creating a 'jitter' of the table output. Tried to create a simple example to capture the issue, but seems intermittent. However, I am seeing it is happening more after I run the code in a debian container and have it launched via shinyproxy.

Installs:
python: 3.10.12
shiny: 0.8.1
shinyswatch: 0.5.1
shinywidgets: 0.3.1

What can be done to stop the classes changing back and forth? Provided is a sample of anapp that has a similar layout to my app im seeing the jitter in, although I could not make the provided sample app jitter

```python
from pathlib import Path
from shiny import App, render, ui, reactive
import pandas as pd
import os

data = {
    "col1": ["mystring value"],
    "col2": ["$123,456,789"],
    "col3": ["$195,000,000,000"],
}
df = pd.DataFrame(data)

app_ui = ui.page_fluid(
    ui.div( 
        ui.div(
            ui.div(
                ui.card(
                    ui.card_header("Section 1", class_="bg-secondary"),
                    ui.output_data_frame("tbl1"),
                    style = "margin-bottom: 10px; min-height: 250px"
                ),
                style = "flex: 1"
            ),
            ui.div(
                ui.card(
                    ui.card_header("Section 2", class_="bg-secondary"),
                    ui.output_data_frame("tbl2"),
                    style = "margin-bottom: 10px; min-height: 250px"
                ),
                style = "flex: 1"
            ),
            ui.div(
                ui.card(
                    ui.card_header("Section 3", class_="bg-secondary"),
                    ui.output_data_frame("tbl3"),
                    style = "margin-bottom: 10px; min-height: 250px"
                ),
                style = "flex: 2"
            ),
            style = "flex: 1; display: flex; flex-direction: column; min-height: 500px; margin: 4px;"
        ),
        ui.div(
            "content here",
            style = "flex: 2; display: flex; flex-direction: column; min-height: 500px;"
        ),
        ui.div(
            "more content here",
            style = "flex: 2; display: flex; flex-direction: column; min-height: 500px;"
        ),
        style = "display: flex; flex-direction: row; width: 100%;"
    )
)

def server(input, output, session):
    # server logic here
    print("server stuff")

    # render results data tables
    @render.data_frame
    def tbl1():
        return render.DataGrid(df, height="95%", width="100%")
    @render.data_frame
    def tbl2():
        return render.DataGrid(df, height="95%", width="100%")
    @render.data_frame
    def tbl3():
        return render.DataGrid(df, height="95%", width="100%")
    

app = App(app_ui, server)
```

**Comment by corey-dawson** [comment]
Seems to be, when the datatable is outputted in the card body (which has display: flex and flex-direction: column), flex grow properties gets passed to the datatable output. Seems to be what was causing the jittering. Fixed the issue by nesting the datatable output inside another div with display = block

**Comment by cpsievert** [comment]
Thanks for the report. Unfortunately I can't seem to replicate with that example. Do the `DataGrid()`'s in the app that you're seeing this in have a specified `height`? If not, I have a felling that specifying a height will help. If that doesn't do it, wrapping each `ui.output_data_frame()` with `ui.fill.remove_all_fill()` will likely get rid of the issue.

**Comment by corey-dawson** [comment]
> Thanks for the report. Unfortunately I can't seem to replicate with that example. Do the `DataGrid()`'s in the app that you're seeing this in have a specified `height`? If not, I have a felling that specifying a height will help. If that doesn't do it, wrapping each `ui.output_data_frame()` with `ui.fill.remove_all_fill()` will likely get rid of the issue.

I couldnt get it to re-create in a simple example, but great recommendation. Going to close the issue with this comment
