### ISSUE TITLE
Should have tests for error console

### ISSUE THREAD

**Issue by wch** [posit-dev/py-shiny#1251]
This is a follow-up to #1060.

We should have the following two tests applications:

- One which tests that the error console correctly detects when an application has an input and output with the same name. There will be a visible error message as show below, and the error will be logged to the JS console. 
<img width="729" alt="image" src="https://github.com/posit-dev/py-shiny/assets/86978/63c6fbf4-37ee-487e-80a0-5f3d254c549f">
 
- One which tests that when the same application is deployed to Connect, it will _not_ show the error message. We want to make sure that the error console is not enabled when an app is deployed to Connect.

**Comment by karangattu** [comment]
Would you want to test the browser console as well for the first case or simply testing that the `Shiny Client Errors` popup is sufficient?

**Comment by wch** [comment]
I think testing for the popup is sufficient.
