### ISSUE TITLE
Feature request: drag and drop ranking/ordering

### ISSUE THREAD

**Issue by ME-researchgroup** [posit-dev/py-shiny#1252]
Hi!

I was wondering if it would at all be possible to implement drag and drop functionality so that a user can specify an order or ranking to a list of items. It would be very convenient for my use case if a user could order rows in a datatable/datagrid, but that may be a long shot.

**Comment by schloerke** [comment]
Currently, this is a stretch goal for py-shiny. It would be a great py-shiny extension package!

There is prior art with sortable.js and `{sortable}` R package: https://rstudio.github.io/sortable/ . The R package was set up to typically sort list of items.
