### ISSUE TITLE
Input select has different margin-bottom if in panel_conditional when in cards

### ISSUE THREAD

**Issue by tnederlof** [posit-dev/py-shiny#1255]
I noticed some weird spacing issues in an app I am developing (my inputs are all in cards).

It looks like my inputs that are not in any `ui.panel_conditional` have a `margin-bottom: 0` from this CSS entry:
```
.bslib-gap-spacing>.bslib-mb-spacing, .bslib-gap-spacing>.form-group, .bslib-gap-spacing>p, .bslib-gap-spacing>pre {
    margin-bottom: 0;
}
```

However, inputs that are in a `ui.panel_conditional` have a `margin-bottom: 1rem` from this CSS entry:
```
.form-group {
    margin-bottom: 1rem;
}
```

As far as I can tell this happens on other inputs as well. It creates weird spacing when trying to use inputs one after another with some in conditionals and some not in conditionals.

[I recreated a simple example here](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMAgujxM6lACZw6EgK4cAOhFVpUAfSVMAvEyVYoAcziaaHADaWoAI0twAFKqauDHDDezEFZTSUsFGAgWZwg3CPcMQig6aTDIxKiuVF9NFjgHQjJHVxckguUwDKyyIokmfILEooBlTLhspihw4lQyDlImW0ziAHdEcrzw6sSQIoBGESLESrAAYTZiDkI4JimhyYAhGbnF5dX1nfw5ifndov2VtbOigF8KquqASjwniNf3t0MYuITR5IQVJ+QhsRoAa1sxAAHs4iGDCJCYZsFgikdChgAVOgKOCfEajQyoFqZfykaQcDqkKCWOEpXzRNFQjH4L6Ejz0vwlRo5YYA6pFbnZABMQ0qBP5kTqDSaLSYbSp4R6ln6gxO4slSXGYA2SD2S2u62mJ22F1RBxuxwkk3OesuBsOtzADz5mqY+P5HqSXtc+OeqlUshorDkADc5I5ORIfGRgRIMiwWJ0IM9BhLiYmA9B0HpROhHBptBx42G5M9nQBdIA)

**Comment by gadenbuie** [comment]
Thanks @tnederlof! It turns out this is the result of two issues:

* https://github.com/rstudio/bslib/issues/1030 would fix the `margin-bottom` discrepancy
* But #1256 is needed for the fix to work in py-shiny

**Comment by gadenbuie** [comment]
Here's [another example](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMAgujxM6lACZw6EgK4cAOhFVpUAfSVMAvEyVYoAcziaaHADaWoAI0twAFKqauDHDDezEFZTSUsFGAgWZwg3CPcMQig6aTDIxKiuVF9-NjhCAGtbYgAPZyIM7Ny85XwmcoBhYpz88okAFToFOABKPBckiMMUtJY4B0IyR1cu7sTygaGyBrHwicmwAGVBzOEocOJUMg5SJltB4gB3RDnKhcWIkHKARhFyxEqwGuIOQjgme7m7gCFH56vd6fW7-Cp3KoA6psN4fL6QsAAXwkFyuTA64wmhlQhWWjE+FDywgyUgw5TamIiGMukUMMTiCSuvQgqT8hFqpUK7MydTyACYfi8OfUKs1WtS0djNoN-KRpBxdqQoJZCn0yNFhWV8JSmR41ZpputRqi0UkpmthgKKibTZFyqsZkxNkxtorwodLCcztadbabmBvkhATDgV8HuCA2CntDYSCwRIIVChbH4eVkfNba4JVds4tsbj8UxCcS5HAyWAKTSqZ0adTK6pZDRWHIAG5yRxqiQ+MisiQDFgsPYQNpnGmoKAD1TqdB6UToRwabQcPutuRtJEAXSAA), modified from @tnederlof's example, that shows the issue:

![image](https://github.com/posit-dev/py-shiny/assets/5420529/020a57f5-2392-416e-a792-161fd6737ec7)

<details>
<summary>App Code</summary>

```python
from shiny import App, render, ui

app_ui = ui.page_fillable(
    ui.layout_columns(
        ui.card(
            ui.input_checkbox("checkbox", "Checkbox", True),
            ui.input_select(  
                "select",  
                "Select an option below:",  
                {"1A": "Choice 1A", "1B": "Choice 1B", "1C": "Choice 1C"},  
            ),
            ui.p("Some text here.")
        ),
        ui.card(
            ui.input_checkbox("checkbox2", "Checkbox", True),
            ui.panel_conditional("input.checkbox",
                ui.input_select(  
                    "select2",  
                    "Select an option below:",  
                    {"1A": "Choice 1A", "1B": "Choice 1B", "1C": "Choice 1C"},  
                ),
            ),
            ui.p("Some text here.")
        ),
    ),
)

def server(input, output, session):
    pass

app = App(app_ui, server)
```

</details>

**Comment by gadenbuie** [comment]
This example also points out that `ui.card()` doesn't have a `fillable` argument, which could have been set to `fillable=False` in this case. Or `ui.card_body()` could be exported so that fillability can be disabled internally at the body level with `ui.card(ui.card_body(..., fillable=False))`.

Related #1128

**Comment by tnederlof** [comment]
Ah very interesting, thanks for checking!
