### ISSUE TITLE
Allow users or third-party packages to replace Bootstrap CSS

### ISSUE THREAD

**Issue by gadenbuie** [posit-dev/py-shiny#1270]
In Shiny for R, all page functions take a `theme` argument, with the following behavior:

* If `NULL`, [use Bootstrap 3](https://github.com/rstudio/shiny/blob/edd1db78e3ba7abfa802b1c98f8a053d010e24ef/R/bootstrap.R#L55-L58)
* If [a scalar string](https://github.com/rstudio/shiny/blob/edd1db78e3ba7abfa802b1c98f8a053d010e24ef/R/bootstrap.R#L39-L42), assume it's a client-side path to a CSS file and add a `<link>` element to the page `<head>`. Note that base Bootstrap 3 is still included in this case.
* If [a bslib theme](https://github.com/rstudio/shiny/blob/edd1db78e3ba7abfa802b1c98f8a053d010e24ef/R/bootstrap.R#L52-L54), add `bslib::bs_theme_dependencies(theme)` but not the base Bootstrap dependency after registering the theme (so that it can be used for runtime Sass compilation).

I'm proposing the following approach to `theme` in Python:

1. `theme=MISSING` ~or `theme=ui.theme()`~ default case
	* Uses the default Shiny Bootstrap theme.
1. `theme: str | Path`
	* Uses `ui.include_css(theme)` to include the CSS file. Shiny's Bootstrap bundle is still added, but without including the Bootstrap stylesheet.
1. ```
   theme=ui.theme(
       theme: str | HTMLDependency | Tagifiable,
       bs_version: Optional[str],
       replace = "css" | "all" | "none"
   )
   ```
	* Allows a CSS file, HTML dependency or a tagifiable that returns an HTML dependency to provide the theme.
	* Includes optional `bs_version` that can be used for runtime checks to warn if the provided Bootstrap theme is out-of-date with Shiny's provided Bootstrap version.
	* Allows theme providers to determine if the theme `replace`s the `"css"` of Shiny's Bootstrap bundle, the entire (`"all"`) Bootstrap bundle, or the theme is overlaid over base Bootstrap (`"none"`).
1. For completeness, `theme` could also be a dict with keys `theme`, `bs_version`, `replace` such that `ui.theme(**dict)` returns a full theme object.

The first two cases can be seen as a short-cut for providing `ui.theme()`, which itself returns a `Theme` or `ShinyTheme` instance.

**Comment by cpsievert** [comment]
I feel uneasy about having an exported `shiny.ui.theme()` that what is mainly a advanced user / developer facing API.

Also, I can't help but feel like `Theme`/`theme` naming is a bit of a misnomer, especially if we're thinking about this as a user facing API. In that case, maybe something like `bootstrap_css()` is better?

In fact, I hate to suggest this, but maybe we don't need a `theme` argument at all for this use case. Could we not have a `bootstrap_css()` that could be dropped anywhere in the UI? Implemented roughly like this?

```python
__all__ = (
    "bootstrap_css",
)

def bootstrap_css(path: Path | str, check_version: bool = True) -> list[Tag | HTMLDependency]:
    # Snoop the version of the Bootstrap CSS file
    if check_version:
        check_bootstrap_version(path)

    return [
        ui.include_css(path),
        HTMLDependency(
            name="bootstrap-css", version=bootstrap_version
        ),
    ]

def check_bootstrap_version(path: Path | str):
    file_path = check_path(path)
    content = read_utf8(file_path)
    # TODO: extract version from Bootstrap's banner, then warn/err if not compatible, and
    # also warn if the version wasn't found?

def bootstrap_deps() -> list[HTMLDependency]:
    return [
        jquery_deps(),
        HTMLDependency(
            name="bootstrap-js",
            version=bootstrap_version,
            source={"package": "shiny", "subdir": "www/shared/bootstrap/"},
            script={"src": "bootstrap.bundle.min.js"},
            meta={"name": "viewport", "content": "width=device-width, initial-scale=1"},
        ),
        HTMLDependency(
            name="bootstrap-css",
            version=bootstrap_version,
            source={"package": "shiny", "subdir": "www/shared/bootstrap/"},
            stylesheet={"href": "bootstrap.min.css"}
        )
    ]
```


Two things to note about this approach:

1. We'd (attempt to) check the bootstrap version automatically. As long as Bootstrap isn't getting compiled in a weird way, this should work.

2. We'd (intentionally) drop the `replace = "all"` feature, but we could bring it back with a `bootstrap_js()` if need be down the road. In general though, the thought of encouraging users to customize the JS gives me the heebie jeebies.

**Comment by gadenbuie** [comment]
> If we're thinking about this as a user facing API. In that case, maybe something like `bootstrap_css()` is better? ... In fact, I hate to suggest this, but maybe we don't need a `theme` argument at all for this use case.

In this case, I agree, we wouldn't want to add a `theme` argument. For naming, I think `ui.include_bootstrap_css()` would fit in well. I'd also prefer to use a property on the `HTMLDependency` to report/check Bootstrap version, but we could fall back to parsing the banner in the CSS file if needed.

**Comment by gadenbuie** [comment]
#1282 shows what `include_bootstrap_css()` would look like. 

@cpsievert can you take a look at the approach? This iteration has a bit more moving pieces, e.g. changes in shinyswatch are required https://github.com/posit-dev/py-shinyswatch/pull/32, and it'd be good to hear your opinion before I get too far down the road.

**Comment by gadenbuie** [comment]
Coming back to this after a bit, I'm not seeing a clear winner between the two proposals.

To summarize the current state of affairs, the core work to be done is to separate the Bootstrap dependencies into CSS and JS components. Having done that, third-party theme providers can focus on providing only the Bootstrap CSS. In other words, at a basic level, everything we need can be accomplished via htmltools dependency handling.

On the other hand, a htmltools-dependency-only approach pushes run-time Bootstrap compatibility checks into third-party packages. I think it would be better for most of the abstractions to live in `py-shiny` instead so they can be re-used and so that we have more control over their implementation in the long run.

As pointed out in https://github.com/posit-dev/py-shiny/pull/1282/files#r1552096813 the htmltools-dependency-only approach also needs to account for multiple calls to a function like `include_bootstrap_css()`. OTOH, using a `theme` argument nicely captures the uniqueness of the Bootstrap theme.

We could certainly do a mixture of both -- which would mean adding a `theme` argument to the `page_*()` functions (along the lines of #1275) while internally using an approach closer to that in #1282.

If we take that approach, though, we'll need to agree on the shape of the data passed into `theme`. In this light, the goal would be to define an a contract that could be used by packages like `shinyswatch` and others to provide Bootstrap themes. This would give us the flexibility for internal modifications in py-shiny, as long as we maintain the contract, but it would require us to settle on key constraints now.

**Comment by gadenbuie** [comment]
Another, radically more simple option from @cpsievert: the `theme` argument only takes a path to a CSS file that is used to replace the Bootstrap CSS.
