### ISSUE TITLE
input.<id>_selected_rows() does not work (at least on Shinylive)

### ISSUE THREAD

**Issue by Assad-AC** [posit-dev/py-shiny#1317]
I had supposed this might have to do with the recent update, and that I was struggling to integrate it. This may still be the case, but examples of code, for example, here: https://shiny.posit.co/py/api/core/render.DataGrid.html. The example given therein works on the webpage fine. But when I try copying the code into a fresh shinylive.io application, it does not. Clicking the rows does not give the expected results.

I hope this was clear enough!

Many thanks

**Comment by wch** [comment]
Hi @Assad-AC, we just released Shiny 0.9.0, and this should be fixed now.
