### ISSUE TITLE
Using `if session` to only run code when session has initialised fails

### ISSUE THREAD

**Issue by pieterjanvc** [posit-dev/py-shiny#1327]
Hello,

Let me show the issue using a very simple reprex:

# Issue
```
from shiny.express import session

if session:
    print("The session ID is:" + str(session.id))
```
Generates the error
```
RuntimeError:
The session attribute `id` is not yet available for use. Since this code
will run again when the session is initialized, you can use `if session:` to
only run this code when the session is established
```
And as you can see I implemented exactly the solution the error message recommended and got the exact same error

# Workaround

It took me a long time to find a workaround which is not documented anywhere so I'm sure it's more of a hack:
```
from shiny.express import session

if hasattr(session, "_process_ui"):  
    print("The session ID is:" + str(session.id))
``` 
It's still pretty clean, so if you think this would be a good general solution, you can just update the error message so others know how to fix this issue too :)

Kind regards

**Comment by wch** [comment]
It looks like that error message needs to be fixed.

An explanation of what's happening:

- With Shiny Express apps, the code in the .py file is run once at startup to generate the UI (which is saved and served each time someone connects), and once for each new user session.
- For the first, UI-generating pass, the `shiny.express.session` is not a real `Session` object, but instead a `ExpressMockSession` object. This is the object which throws errors when you try to access the `.id` member.
- For the user sessions, `shiny.express.session` is a `Sesssion` object, and accessing members of it will work fine.

I think it would make sense to add a method to `ExpressMockSession` and `Session`, which reports whether it is a real session object.

For the moment your workaround should be OK. Or you can use this, which is slightly less hacky:

```py
from shiny.session import Session
from shiny.express import session

if isinstance(session, Session):
    print("The session ID is:" + str(session.id))
```

**Comment by wch** [comment]
In #1331, we added a new method `.is_stub_session()`. So with the development version of shiny, you should be able to do:


```py
from shiny.express import session

if not session.is_stub_session():
    print("The session ID is:" + str(session.id))
```
