### ISSUE TITLE
I want a layout with 2 sidebars (one left, one right)

### ISSUE THREAD

**Issue by sidviny** [posit-dev/py-shiny#1350]
Hi,

I would like to get a layout with 2 sidebars, one on the left, one on the right.  The center would be the real page data.

I can't seem to do it, maybe because I still haven't figured out how to use all the elements.  Best I had, was a left sidebar, content split and in that one a right sidebar.  But the margins and/or paddings were not correct and I have whitespace around the right sidebar

**Comment by cpsievert** [comment]
[Here's an example](https://rstudio.github.io/bslib/articles/sidebars/index.html#nested-sidebars) of how todo this in R, and here is [the Python equivalent](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMAgujxMArhwA6EOWlQB9aUwC8UjligBzOEpocANkagAjI3AAUcppoxsAjDbAAZODWFQIAEyZ0OHTZhFg4fODMoOhl8JkJTFhYldSYY1AAPAFoAZiYYbByYgEo8W3tTbGJJMiVQ8Mi6Gwg7O2kMOoiol3dPVjDO6LASstatCqqajoamltn7Ka6YgCVA4L76qJiJAVCyDlIUmICgsi2mYlRKFIByeOIWOB9r4ea5uxiAWSguONIKchYWxGczMgnCdBSADEoEYHsCXrNQXRwUo6FAfBxJCwoTCHqVXnZDCZzJYUgAVOiSOD42bxKCJZIaNKZAAMMTKRTknPkvg8rDgdAAbgKrFxUNUiohgah6YCeYoUmJUFZFCoOBIAHKkOBFMAAXwAukA):

```python
from shiny import App, ui

app_ui = ui.page_fillable(
  ui.h1("Left and right sidebar", class_ = "px-3 my-3"),
  ui.layout_sidebar(
    ui.sidebar("Left sidebar"),
    ui.layout_sidebar(
        ui.sidebar("Right sidebar", position = "right", open = 'closed'),
        "Main contents",
        border = False
    ),
    border_radius = False,
    fillable = True,
    class_ = "p-0"
  )
)

def server(input):
    pass

app = App(app_ui, None)
```

**Comment by sidviny** [comment]
Thank you !

Seems the extra class_ stuff solves the problem.
