### ISSUE TITLE
Conditional @render.download button in shiny express

### ISSUE THREAD

**Issue by isthisthat** [posit-dev/py-shiny#1365]
Hello, is there a way to condition (or `@render.ui`) a `@render.download` button in shiny express? My specific use-case is if a row is selected in a `DataGrid`, show the download button. Thanks!

**Comment by wch** [comment]
You can use `render.express`, which is similar to using `render.ui`, except where `render.ui` requires the function to return the UI components, `render.express` allows you to write code with Express syntax, where the UI components are automatically captured from evaluating the code.

[Live example](https://shinylive.io/py/examples/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACVKMgCwBsBLAIye4xUxOmSYAFNuwA6EeoyYBndtwjYMcAB6o6cRYoFCRYgK7c8TXRAAmcOha069i7jWwXVqE2VmyzGT28AfUU4TjhCMgAKaTBlYgB3IJVbWItYgGV2RKYRJhS4JmtEiE5iKGs0phBYgtjEJliACW5U-Ea47IT6jqzE2IBfAEpfCFkAAStbOg1tXX1ZWxoikrKKoLMoocRZJj2BZcCyDHikgq2mAF5LjtP60f3HpknKaYxihNLy6y3dp72litPmtrABGLY7CD-f6sDhXCRSKJBII0bjhZFDLBQKxiAD0HRgZEI2MUGEIigAbrE-tD9royCY6FDFGQ6FFYewRhAwAM8OBoPBqITiXRSeSKfgiKQKFRkLEhABzNKxQjYTjKsDWbiKVAa9i6-Cxax0NgahI+Q1gACOoUIGopig1sA1Crg2I1It41IgACZQXgAGx4UEBgAMwdB4YAzBgAJx4H0YAM+4MBjAAFiD4f96bw6dkfsDqezkbwMfjiYAHAB2ACswerGFDKezebzBarbcjlbwsajZYwlfriajKdBlaT-qnXYLoIzRZ9tZ7oNLMdDPZjfvroNjGdz-ujwdk44w1bwG7DDfrMdB173DabLbwh59x4n-qDPsXwdDw9PQZjTME1DDAv2DZ8yyPCBQXTDB+wvcMfXTO9CxjWsz1vQdc3DQ9819WDc33TNT0DFMYwDeMbwrVtw1zV9fU7IiQJ7WM71jMiMFvBNE3jA823ondQKLENGyDUEfX7csOPTfcJ37PjCOPRsezEgNRODCSB3YgcZODCdeIgxToLTXMex9OtBz06MmzPWDQwwxtsIgySlLg88Ews5dK2s+yB2reT1JwyCo2PWshLMzyrIHXyY2rLyIMPELoJA0y82rFMfV-BM437MLv1BRtYx7IL+zwyN5x7TNEK43KMyQh9KyfXDj1gs9KvTRCo2szSwqjZCH3TJrILw0d51zOKSIDIM7LMoTBPTDDwP3WQurGvALLPWsU1gvtg0nbcJy28CcwTFbyzbas5w-etYLAudKyjbddwMk7QVnDAbo0kD-VjM9YuyzNhxA0Np0PN7oLC+sN3HYNa0Q-8ByOkNBzPErToh8Ky1Dfc4YHGqM0eh9+zRgSY3gstcaQu9-IHSscYzPjmug3cU0q0NszraKNyw7dGyykmC0bUr1vjKa8ybZccoOuNjpnX1pq+tzYxzAnspg1MSNbYcVpSttWM4iNJNPDCPtBeS0xevBtYxnsN1rf0fQDQjQI4grg1g+stfbZnJvd3m72TbLqwwyGIP9esA1C9yuv9KNCbQ3M0Iw2Cs3AqH3sIjSp1DeNYJXIOvKTWW6NkHkAF0gA)

```py
from pathlib import Path
from shiny.express import ui, render, expressify, input

ui.input_select("show_hide", "Show or hide download", {"hide": "Hide", "show": "Show"})


@render.express
def download_ui():
    if input.show_hide() == "show":

        @render.download()
        def download1():
            path = Path(__file__).parent / "mtcars.csv"
            return str(path)
```

**Comment by isthisthat** [comment]
Wow that worked beautifully! Thanks @wch!
