### ISSUE TITLE
Datagrid selection and filtering may break app

### ISSUE THREAD

**Issue by Will-S-Revmed** [posit-dev/py-shiny#1390]
This is on version 0.9.0
It appears that, when using the built in filters on datagrids, if any rows are selected, the datagrid may break (becomes unresponsive, graphical errors). It also breaks the entire app with it in my experience, in particular, other datagrids become unresponsive.

Minimal example:
```
import pandas as pd
from shiny import App, render, ui

df = pd.DataFrame(data={'a': [str(i) for i in range(10)]})

app_ui = ui.page_fluid(
    ui.output_data_frame(id='my_df')
)


def server(input, output, session):
    @render.data_frame
    def my_df():
        return render.DataGrid(
            data=df,
            filters=True,
            selection_mode='rows'
        )


app = App(app_ui, server)
```

To recreate the behaviour, first select a row, and then type in something in the filter such that the selected row won't appear. The data grid will subsequently break. It seems like the conditions under which the bug occurs are when what is typed in the filter will exclude any of the selected rows.

**Comment by schloerke** [comment]
Thank you @Will-S-Revmed for the great reprex! The fix is in `main` and ready for the `v0.10.0` release tomorrow
