### ISSUE TITLE
How to download files using web links and render.download func?

### ISSUE THREAD

**Issue by Linhkust** [posit-dev/py-shiny#1401]
Hello, i have a ui.download_button:
` ui.download_button('download', 'Download', class_="btn-success")`

And i have a function which read the string of ui.input_text, such as "Hong Kong", then the func will retrieve a unique ID for Hong Kong and create a download link based on the ID. Lastly, Shiny will download the zip file based on the link. How can I achieve  that?

The download func is:

```
 @ render.download(boundary.gz)
    def download():
        search_query = input.area()
        headers = {'User-agent': 'Mozilla/5.0'}
        # osm id
        id_url = "https://nominatim.openstreetmap.org/search?q={}&format=json".format(search_query)
        r = rq.get(id_url).text
        osmId = json.loads(r)[0]['osm_id']

        # boundary file
        url = 'https://osm-boundaries.com/Download/Submit?apiKey=6a162f090cd46e501debec8ce92db0bc&db=osm20240205&osmIds=-{}&format=GeoJSON&srid=4326&includeAllTags'.format(
            osmId)
        down_res = rq.get(url, headers=headers)
        with open('{}.gz'.format('boundary'), 'wb') as file:
            file.write(down_res.content)

        return file
```

**Comment by gadenbuie** [comment]
I think maybe you're wanting this?

```python
@render.download(filename="boundary.gz")
def download():
    # ... the code as you have it written
```

You might want to take a look at the [render.download documentation](https://shiny.posit.co/py/api/express/express.render.download.html) for additional help. 

If my suggestion above doesn't work, can you please provide a complete, runnable Shiny app?

**Comment by frozenoffical** [comment]
my code downloads files from a direct download link ... when i run it on pc ... but when i deployed it on render free web instance it dont download it ... how to fix

**Comment by gadenbuie** [comment]
@frozenoffical can you please open a new issue with a complete reproducible example?

We haven't heard from the original post author in a while, so I'm going to close this issue.
