### ISSUE TITLE
Guide To Busy Indicator Use?

### ISSUE THREAD

**Issue by gfleetwood** [posit-dev/py-shiny#1433]
Hello,

I'm trying to use the busy indicator feature incorporated [here](https://github.com/posit-dev/py-shiny/pull/918), but its behavior is seemingly erratic. Sometimes it works, and other times it doesn't.  After looking through the examples I'm still not clear on how to make it work consistently:

* https://github.com/posit-dev/py-shiny/blob/main/examples/busy_indicators/app.py
* https://github.com/posit-dev/py-shiny/blob/main/shiny/api-examples/busy_indicators/app-core.py

This is the structure of the code I wan't to use the feature in. When a button is clicked the code fetches dataframes from several sources and displays them on the UI. How do I use the busy indicator feature to always have a loading symbol as each bit of information is gathered?

```
from shiny import App, reactive, render, req, ui
from shiny.ui import TagList, div, h3, head_content, tags
import pandas as pd 
import requests

def server(input, output, session):

    @render.data_frame
    @reactive.event(input.search_button)
    def get_df():

        server_endpoint = 'https://'
        payload_in = {'search_term': input.search_term().strip()}

        #ui.busy_indicators.options(spinner_type = 'ring'),
        #ui.busy_indicators.use(spinners = "ring"),
        response = requests.post(server_endpoint, json = payload_in)
        payload_out = response.json()['data']
        result = render.DataGrid(pd.DataFrame(json.loads(payload_out)), width = '1000px') 

        return(result)

    @render.data_frame
    @reactive.event(input.search_button)
    def get_df2():

        server_endpoint = 'https://'
        payload_in = {'search_term': input.search_term().strip()}

        #ui.busy_indicators.options(spinner_type = 'ring'),
        #ui.busy_indicators.use(spinners = "ring"),
        response = requests.post(server_endpoint, json = payload_in)
        payload_out = response.json()['data']
        result = render.DataGrid(pd.DataFrame(json.loads(payload_out)), width = '1000px') 

        return(result)

app_ui = ui.page_fluid(

    #ui.busy_indicators.options(spinner_type = 'ring'),
    #ui.busy_indicators.use(spinners = "ring"),

    ui.input_text('search_term', 'Enter Search Term'),
    ui.input_action_button('search_button', 'Search'),    
    ui.output_data_frame('get_df'),
    ui.output_data_frame('get_df2'),
)

app = App(app_ui, server)
```

@cpsievert

**Comment by cpsievert** [comment]
Are you able to screen share the behavior you're seeing and/or provide search terms that I can enter into the example to replicate you're seeing?

[Here's a more minimal version of this app](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMASxlWICcyACVKCAEygGcXe2nADoQRAM0bEYLHgAsaEbCzoNmLAILo8LRnCiEyNAG5xturnEZm4AR20BXGuMnS5C7BkfL6TVgBUoAHMAGRoeMm1OY21ZAGYYvU4AfRJySgiWMiCeEVyLMRlLE0YACgVUewziSoqMnjgeHhpSAEpEPJZOlgABc05LDG4spIlYOBEunt19QxMMOBNyMohajHqoRkJZJIAjSrJWia7+gsC4MiTOMRK2o8nOlV9MunHRCHuuw3g1gBs4OFQJQALC0Oh8WFcWABeQQYAAiUCyADFGGMSndwZ0QBjMZMhGB1PjECxgABGbQAJm08RYQIAungcbjOviAEJEkkAVm0ADZtAB2bQADgZTOZ+IAwhzgABObSkgAM8vJLFJFNF72ZLAAvmKWKC3pjdGR7Ix3n0BgisgBxRg0TglK7aADu9rIsih+MVCoVqAAHviDRjepR+oxBoioCNUfBg9MDMY4PNFmRlqt1pttnsyAcIAbJicWGcLlcKTd2pqPo81F9Xnra79-oCQWCPpCYahOPDIyi0XrJtjK1qWQTpSqqSwafTGUPh2zpdyWHyWIKWCKZ8O8WApUgSXLVUrVSq1Rrh7rZ10gxfOsbTe8Shbw1aoLb7Y6xC63R6vT7fQGwC0V4iGgqBJF4MKOFgQRwCMPyOA6GKQXsPDYEkChRIQiJMDwGDEKghikDwJQ8KgCgQJYSRkNgqBwJ6YA7BsOQARuXSQeUlSUXAfqpviGZbJxjAwPi2j4gAomkjAsAAynomYsH4lhCcxiE0Bg7EXDMzQQLs+ykOiYB8VmumiPgLD4jJGxbIGLGdJB1RkLUlyRtGfZgMWlxiNZKm4TUHFDFGozwPp7mll5eZ5CB0IaOgJQgWBNDaPUjDFAaYDanSQA) (without the requests to an unknown endpoint) that works as expected.

BTW, as pointed out in the [docs](https://shiny.posit.co/py/api/core/ui.busy_indicators.options.html), make sure to always include `busy_indicators.options()` and `busy_indicators.use()` in the UI (calling them that way in the `@render.data_frame` decorator won't do anything).

**Comment by gfleetwood** [comment]
@cpsievert Can I privately message you a video or screenshot? The actual app is a bit sensitive. 

I was trying to use the feature - pip installing from git - before it was on pypi and the docs went up, but now I have an understanding of how it should be used. That's what I wasn't sure about before, so it was hard to know where the erroneous behavior was coming from. 

What i just noticed is that the busy indicators always work when I test the app locally. The problem occurs when I deploy it to Modal (https://modal.com/). So now I know that's where I should be looking.

On another note, do you know anyone who does Shiny For Python consulting?

**Comment by cpsievert** [comment]
To summarize the email thread, after updating shiny on the hosted environment, the issue went away
