### ISSUE TITLE
Unexpected difficulty starting out with py-shiny

### ISSUE THREAD

**Issue by nirguk** [posit-dev/py-shiny#1452]
I tried following the two step process; I understood these to be terminal commands to issue
Getting started with Shiny is easy:
1 pip install shiny
2 shiny create --template dashboard-tips

The first one seems to execute; though it does mention default to user installation rather than normal site-package due to write permissions, but ultimately something is installed. presumably shiny ?
Step 2 simply fails with shiny being an unrecognised symbol :
```
shiny : The term 'shiny' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that the path is correct and try a...
```
Was having installed shiny supposed to produce some sort of executable cli ? a shiny.exe somewhere ?

**Comment by cpsievert** [comment]
Hi @nirguk, would it be possible to share the output that `pip install shiny` produces? It should create a CLI via the [click](https://click.palletsprojects.com/en/8.1.x/) package.

**Comment by gadenbuie** [comment]
We're happy to help but we haven't heard back in over a month. I'm going to close this issue for now.
