### ISSUE TITLE
Programmatically unselect a selected row in a rendered dataframe

### ISSUE THREAD

**Issue by DvGils** [posit-dev/py-shiny#1458]
Is it possible to programmatically unselect a row that the user has selected?

Currently, if I define logic to be ran when a user selects a row, the row stays selected and the logic will trigger again unintentionally at a later time (e.g., the user presses a button that opens a modal, when they close the modal the logic from the selected row will trigger again).

**Comment by schloerke** [comment]
Using a combination of [`mydf.update_cell_selection()`](https://shiny.posit.co/py/api/core/render.data_frame.html#shiny.render.data_frame.update_cell_selection) and [`mydf.input_cell_selection()`](https://shiny.posit.co/py/api/core/render.data_frame.html#shiny.render.data_frame.input_cell_selection) you should be able to achieve this. 

Example shinylive app:
https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbDOAD1R04LFkw4xUxOmTERUAVzJ4mQiABM4dZfI4AdCPUatO3MRKkyhUQmQ4A3OMqEBHfeMnSmqKOqii-Xmr6+mo0TAC8gRgAIlBkUABidLBwABQgumB8mYhMwACMygBMALrKmdg5eZlQmeVgAEaZJQC+AJTBEPoAAqoadBhqcVAA+vQpIXBhMNihqW2I+kzLKnBk8nQQq+qaMcMA4nQcaqmhyixwADZwNhykIzDEGuGZDADumR1d371w1rYOXg0Gg3MiTMIjeaLLYrQhXS4jC7XW6kCJMGahDBwy4IpGgu4QeZLFZ+C6ebG4q740jATJkbCoODNCKRV7ED5gYnLPE2OBqEbvUSRCmIqkoiC0sCC5pcsRha6EnkUfmCtpMAB8TAADNCVnqmDoMI8hri2OzUobjVBLqlZfqVoaACpQADmABkOCwyLawABlMXKlTspgQeQwBqaXJ1VgBvkC9ksYBakptPB2+1MADETAAqhcmAADLgKMgjf4EkYNRRkUgFpg+NQh4gyAuWp7WyvV2tMGtMQhodZCHtsOB9y4cQgAayYcAc5BY6ftNGIzc04UNxcUZfFnbINcJmTUnpgnpYD3bl2jmWix9PnzTMIzKz+LGwI0Il2IF3CCWtF0XTBtF8PRWLcgJTCCNggX8YFwLwc7epuZCDLeIjniaXx+NgECEEwGgQlCspQG8UAcDIGI0Bg8ioEMFDvvCorIrYpCpAAcqQcBfHqbYmgKcCPA48xgC0JRAA

Note: I had to use `input_action_button` and not `modal_button` to capture the click events
