### ISSUE TITLE
data_frame coerces datetimes to integers

### ISSUE THREAD

**Issue by machow** [posit-dev/py-shiny#1477]
Note that some_date is a datetime column below, but gets displayed as an integer (from epoch?)

```python
from shiny import render
from shiny.express import ui
import pandas as pd


ui.h2("Palmer Penguins")


@render.data_frame  # <<
def df():
    df = pd.DataFrame({
        "some_date": pd.to_datetime(["2021-01-01"])
    })
    
    return render.DataGrid(df)  # <<
```

![image](https://github.com/posit-dev/py-shiny/assets/2574498/c2bad824-80e5-4f5f-b789-b23b346b71ee)

**Comment by schloerke** [comment]
Fixed here: https://github.com/posit-dev/py-shiny/commit/08cd1f02b49c2ec91df6916e7f8c44f22363b005#diff-f3a80a7f4e0350ee4a9b308871b42e1222b812528ce9de3a275b0774370b21c5R73-R76

Running the same app code, it now displays:
![Screenshot 2024-07-10 at 9 46 09 AM](https://github.com/posit-dev/py-shiny/assets/93231/e8a46b9b-2d35-4b19-9a14-35d2797a1577)
