### ISSUE TITLE
Remove `@output` from Python/R comparison article

### ISSUE THREAD

**Issue by gadenbuie** [posit-dev/py-shiny#1516]
Seen in a few places here https://shiny.posit.co/py/docs/comp-r-shiny.html

**Comment by Sherwin-14** [comment]
Hey as far as I understand the @output decorator is to be removed from the entire page isn't it? If yes Can I take this up?

**Comment by jcheng5** [comment]
@Sherwin-14 Yes—and sure, we’d appreciate the help! https://github.com/posit-dev/py-shiny-site/blob/main/docs/comp-r-shiny.qmd

**Comment by Sherwin-14** [comment]
https://github.com/posit-dev/py-shiny-site/pull/196
