### ISSUE TITLE
AttributeError: module 'shiny.ui' has no attribute 'input_task_button'. Did you mean: 'input_action_button'?

### ISSUE THREAD

**Issue by francis-bayezian** [posit-dev/py-shiny#1521]
I  am using pyhton 3.12.1 and using shiny-0.10.2 but I get the error AttributeError: module 'shiny.ui' has no attribute 'input_task_button'. Did you mean: 'input_action_button'?

**Comment by wch** [comment]
Are you sure that you are running Shiny 0.10.2? Sometimes Python environments can get mixed up.

Can you put this at the top of your app to confirm?

```py
import shiny

print(f"Shiny version: {shiny.__version__}")
```

**Comment by francis-bayezian** [comment]
Thank you, the problem is solved now

**Comment by wch** [comment]
Good to hear that!
