### ISSUE TITLE
shinyswatch themes broken in py-shiny 1.0.0

### ISSUE THREAD

**Issue by DvGils** [posit-dev/py-shiny#1561]
Shinyswatch no longer seems to work correctly in the newest version of shiny.

For instance, input selectize now looks like below using `shinyswatch.theme.darkly()`:
![image](https://github.com/user-attachments/assets/f307a505-572d-41b0-bf53-48c3bf8ef6fb)

And I get this in the console: 
`INFO:     127.0.0.1:59190 - "GET /lib/bootstrap-js-5.3.1/bootstrap.bundle.min.js.map HTTP/1.1" 404 Not Found`

Worked correctly in the previous version and it looks fine when I don't set a shinyswatch theme:
![image](https://github.com/user-attachments/assets/29479daf-39ed-4e05-8ebb-13340bb6eb4a)

**Comment by schloerke** [comment]
Please see https://shiny.posit.co/blog/posts/shinyswatch-0.7.0/#migrating-to-v0.7.0 on how to migrate using the latest `shinyswatch`.

Closing for now. If the issue still persists, please comment below with your pip list and enough app code to reproduce the problem. Thank you for the quick issue!
