### ISSUE TITLE
`shiny create` always create `"basic-app"` folder even an app folder is given 

### ISSUE THREAD

**Issue by yoonghm** [posit-dev/py-shiny#1571]
I use `shiny create -t basic-app -d 01-app` to create a Shiny app under the `"01-app"` folder using `basic-app` template. However, `basic-app` folder is always created.

I am using Shiny 1.0.0.

**Comment by wch** [comment]
Sometimes if you `pip install shiny`, the `shiny` command-line script might still refer to a different installation of Shiny.

What do you get if you run `shiny --version`? It should look like this:

```
❯ shiny --version
shiny, version 1.0.0
```

**Comment by yoonghm** [comment]
Hi,

`shiny --version` show 1.0.0.

**Comment by yoonghm** [comment]
The problem disappeared after my computer is restarted.  Strange.
