### ISSUE TITLE
shiny 1.0.0 breaks app in Firefox

### ISSUE THREAD

**Issue by gernophil** [posit-dev/py-shiny#1578]
I have two action button and one of them is disabled. These I invoke using:
```
...
ui.input_action_button("button1", "description"),
ui.input_action_button("button2", "description", disabled=True)
...
```
The button both appear and button2 is also disabled. If I try to enable it by pressing button1 in an function call using
```
@reactive.event(input.button1)
def press_button1():
    ui.update_action_button("button2", disabled=False)
```
I get an error:
```
Error:
update_action_button() got an unexpected keyword argument 'disabled'
```

According to [this](https://shiny.posit.co/py/api/core/ui.update_action_button.html#shiny.ui.update_action_button) the  `ui.update_action_button` should take the `disabled` argument. What's wrong here?

**Comment by gadenbuie** [comment]
Are you sure you're using shiny v1.0.0? The `disabled` argument was just added in that version. Try adding `shiny.__version__` somewhere in your UI to confirm.

**Comment by gernophil** [comment]
Ah yes, I was still on 0.10.2. I tried to update to 1.0.0, but this completely broke my layout of my two apps. I'm using
```
app_ui = ui.page_fillable(
    ui.panel_title(
        ...
    ),
    ui.layout_sidebar(
        ui.sidebar(
            ....,
            width="350px"
        ),
        ui.layout_columns(
            ui.card(
                ...,
                full_screen=True
            ),
            ui.card(
                ...
                full_screen=True
            ),
            col_widths=[12, 12]
        )
    )
)
```

**Comment by gadenbuie** [comment]
Are there any error messages in the browser dev tools console? (Right click anywhere on the page, select "Inspect" or "Inspect element", choose the Console tab.)

**Comment by gernophil** [comment]
Don't really know, what to look for here. Not many objects to inspect :D. However, this clearly seems to be an incompatibility with firefox. I made this dummy app:
```
from shiny import App, render, ui, reactive
from pathlib import Path


app_ui = ui.page_fillable(
    ui.panel_title(
        ui.row(
        ui.column(6, ui.h1("title1")),
        ui.column(6, ui.h1("title2"))
        )
    ),
    ui.layout_sidebar(
        ui.sidebar(
            ui.input_text("input_text1", "input_text1", value=""),
            ui.input_text("input_text2", "input_text2", value=""),
            ui.input_text("input_text3", "input_text3", value=""),
            ui.input_text("input_text4", "input_text4", value=""),
            ui.input_text("input_text5", "input_text5", value=""),

            ui.input_selectize("input_selectize1", "input_selectize1", choices=["1", "2"]),
            ui.input_numeric("input_numeric1", "input_numeric1", value=4),
            ui.input_numeric("input_numeric2", "input_numeric2", value=8),
            ui.input_numeric("input_numeric3", "input_numeric3", value=20),
            ui.input_selectize("input_selectize2", "input_selectize2", choices=["3", "4", "5"]),
            ui.input_numeric("input_numeric4", "input_numeric4", value=1),
            ui.input_numeric("input_numeric5", "input_numeric5", value=1),
            ui.input_switch("input_switch1", "input_switch1", value=False),
            ui.input_switch("input_switch2", "input_switch2", value=False),
            ui.input_switch("input_switch3", "input_switch3", value=False),
            ui.input_action_button("input_action_button1", "input_action_button1"),
            ui.input_action_button("input_action_button2", "input_action_button2", disabled=True),
            width="350px"
        ),
        ui.layout_columns(
            ui.card(
                ui.card_header("card_header1"),
                ui.output_data_frame("card1"),
                full_screen=True
            ),
            ui.card(
                ui.card_header("card_header2"),
                ui.output_data_frame("card2"),
                full_screen=True
            ),
            col_widths=[12, 12]
        )
    )
)


def server(input, output, session):

    @reactive.event(input.input_action_button1)
    def reactive_function1():
        pass

    @output
    @render.data_frame
    def card1():
        return reactive_function1()

    @output
    @render.data_frame
    def card2():
        pass

    @reactive.effect
    @reactive.event(input.write_guides)
    def reactive_function2():
        return reactive_function1()

src_dir = Path(__file__).parent / "src"
app = App(app_ui, server, static_assets=src_dir)
```
Then I started it and opened it with safari (left) and firefox (right).

With 0.10.2 both browsers seem fine:
![Bildschirmfoto 2024-07-26 um 21 16 03](https://github.com/user-attachments/assets/c1a40577-6341-40c5-b952-7fb99cb3330e)

But as soon as I switch to 1.0.0, Firefox fails, but Safari is still able to display:
![Bildschirmfoto 2024-07-26 um 21 15 10](https://github.com/user-attachments/assets/6fbc60a6-2487-4195-a7c3-a326bdfc7373)

Not sure, if this is of any use, but I can "expand" the sidebar in Firefox leading to this:
![Bildschirmfoto 2024-07-26 um 21 15 21](https://github.com/user-attachments/assets/4f2d318f-809b-463d-9c99-7c2a8670397d)

**Comment by gadenbuie** [comment]
> Are there any error messages in the browser dev tools console? (Right click anywhere on the page, select "Inspect" or "Inspect element", choose the Console tab.)

Sorry, by "browser" I mean in Firefox where the app doesn't appear as expected. Open the broken app, then in Firefox right click on the page. Choose "Inspect Element" and then find the "Console" tab in the panel that opens. There will likely be a bunch of red console messages there. Take a screenshot of what you see at that point.

**Comment by gernophil** [comment]
Ok, right-click doesn't seem to work in FF, but `F12`. So, here's the console after starting the app using shiny 1.0.0 and connecting via FF:
![Bildschirmfoto 2024-07-27 um 01 17 41](https://github.com/user-attachments/assets/55b9b7c4-f404-48fd-9322-3838e2dfa7d8)

Just for comparison here the same with 0.10.2:
![Bildschirmfoto 2024-07-27 um 01 17 05](https://github.com/user-attachments/assets/72b72985-eef5-4e29-86fb-25668ca51a2b)

**Comment by gernophil** [comment]
Ha, I had to delete the Firefox cache and website settings and now it's working. Didn't think on such an easy solution :D.
