### ISSUE TITLE
`Chat()` doesn't work inside a module

### ISSUE THREAD

**Issue by cpsievert** [posit-dev/py-shiny#1581]
Currently the `id` in `Chat()` isn't getting namespaced properly inside a module, which is why [this minimal example](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMAgujxMYxACYBXADZwJsjgB0I69QAEpcxRhXrpcGk0JsoZAPq6rKgBQBKROqZumdOGVl0ITFRjmlnYc9hzSALyqRBZk0Y6aGhA6MgpwGCxwdABuWUYmZrE2MlaZOVlhEKiyZBLENdW1rHAsLBykzq7uQcIR-hwYAMKxYZHRPfGJ7kxaPRikdmWlsgBGMBxxfu5QLNgQhEzGplZOLlvTbrJlTH1zV1lWXI1OXRdMUADuUBuFlhhoqEo0hsLRYUAA5nB7DRogBNeqsb7SRBMED3OgAX0mSXUAJCN36WAhcCsNA48nkUBWinsr0JqCgEDg8isZA2NOiAAlmfJiEwAMqcbhMYaWeJ4Ok9YrAhzRGjEYjiulkilUxTFFbkuARAAqdFkSnUCRxECOzXKdEqjTqDRqEkyrXaEE651+1lsZVylrlCuxiQBBLEqHseJU9qyXuNYAxAF0gA) doesn't reply back when a input is submitted.

```python
from shiny import App, module, ui


@module.ui
def chat_mod_ui():
    return ui.chat_ui(id="chat")


@module.server
def chat_mod_server(input, output, session):
    chat = ui.Chat(id="chat")

    @chat.on_user_submit
    async def _():
        user = chat.user_input()
        await chat.append_message(f"You said: {user}")


app_ui = ui.page_fillable(
    ui.panel_title("Hello Shiny Chat"),
    chat_mod_ui("foo"),
    fillable_mobile=True,
)


def server(input, output, session):
    chat_mod_server("foo")


app = App(app_ui, server)
```

**Comment by taysharaf** [comment]
I am still facing the same issue, do I need to change anything with the simple example to make it work?

**Comment by cpsievert** [comment]
This fix hasn't yet made it's way to pypi (it should within the next few days).

If you want the fix in the meantime, install with `pip install https://github.com/posit-dev/py-shiny/tarball/main`

**Comment by taysharaf** [comment]
thanks, I install the dev version, added git+ before "https" for the install command to work, and the chat is working now within the module
