### ISSUE TITLE
Version 1.0.0 not stable with sidebar

### ISSUE THREAD

**Issue by yreynaud** [posit-dev/py-shiny#1588]
ui.panel_sidebar is not defined in the latest versions (1.0.0). 

First I refered to the documentation to see the new way of implementing a layout sidebar that contains a panel_sidebar and a panel_main; and I noticed that the documentation also contains this problem (https://shiny.posit.co/py/layouts/arrange/#controlling-for-page-width-and-height)

At the same level, panel_main is not defined.

Previously using versions under 1.0.0, I had not any problems with sidebars.

I don't know if it is a mistake, or if it is only the documentation that hasn't been updated

**Comment by gadenbuie** [comment]
Hi @yreynaud, thanks for opening the issue, we'll get the documentation updated ASAP. `hi.panel_main()` and `ui.panel_sidebar()` have been deprecated since shiny v0.6.0 (if I remember correctly) and were removed from v1.0.

Instead of `ui.panel_sidebar()`, you can use `ui.sidebar()` and you can unwrap the items in `ui.panel_main()`, passing them directly as children to `ui.page_sidebar()` or `ui.layout_sidebar()`.

**Comment by yreynaud** [comment]
Hello @gadenbuie, thank you for your answer !
In fact, I saw that I could use these methods in the sidebar documentation. But trying to use these methods, I didn't have the exepected results. Here is an example of the application ui I want to create
```python
title = 'My app title'

# Lists to store the ui items of the sidebar and the main panel
sidebar_items = []
main_items = []

app_ui = ui.page_fluid(  
            ui.head_content(
                ui.tags.style("""
                                .title {
                                    font-size: 24px;
                                    margin-bottom: 20px;
                                }}
             
                            """)
                        ),
           ui.panel_title(ui.h2(title),
                           {"class": "title"}
                           ),
            ui.div(
                ui.input_action_button("logout_btn", "Logout", class_="btn-danger"),
                style="float: right;"
            ),
            ui.layout_sidebar(
                ui.panel_sidebar(
                    ui.output_ui(id='username_output_text'),
                    *sidebar_items,
                ),
                ui.panel_main(
                    *main_items
                ),
            ),
```  

Here is an example of the new implementation I used for layout_sidebar:

```python
ui.layout_sidebar(
                ui.sidebar(
                    ui.output_ui(id='username_output_text'),
                    *sidebar_items,
                    open='open',
                    position='left'
                ),
                *main_items,
            ),
```

The problem is that with this implementation, the sidebar isn't located on the left, but under the main content : 
![image](https://github.com/user-attachments/assets/e1d0dd58-0640-4a13-9e88-820e18068221)

**Comment by gadenbuie** [comment]
Can you try doing a hard page refresh, or clearing the browser cache and then reloading?

**Comment by gadenbuie** [comment]
Glad that worked! I'm going to leave the issue open for now, I'll close it when I fix the docs.
