### ISSUE TITLE
the doc on the styles argument of render.DataGrid() is incorrect: snake-case works

### ISSUE THREAD

**Issue by shrektan** [posit-dev/py-shiny#1591]
It says:

style: A dictionary of CSS properties and values to apply to the selected rows and columns. The keys must be _camelCased_ CSS property names to work properly with react.js (e.g. backgroundColor instead of background-color).

<img width="681" alt="image" src="https://github.com/user-attachments/assets/d9395db6-6eef-4e2b-8c98-062d7f99b92b">

However, the following code works.

```python
...
styles = [
  {
      "style": {"text-align": "center"},
  },
  {
      "cols": num_cols_idx,
      "style": {"text-align": "right"},
  },
  {
      "rows": list(range(1, df.height, 2)),
      "style": {"background-color": "#f9f9f9"},
  },
]
return render.DataGrid(df, filters=True, styles=styles)  # type: ignore
```

<img width="910" alt="image" src="https://github.com/user-attachments/assets/a1828422-c44a-4095-a7f1-6499d629236e">

**Comment by schloerke** [comment]
Thank you! Addressed in #1595
