### ISSUE TITLE
data frame not showing using ui.output_data_frame

### ISSUE THREAD

**Issue by jwijffels** [posit-dev/py-shiny#1601]
I'm using Python 3.12.4 with the latest version of shiny with the following example code but the data frame does not show up

```
from palmerpenguins import load_penguins
from shiny import App, render, ui

penguins = load_penguins()

app_ui = ui.page_fluid(
    ui.h2("Palmer Penguins"),
    ui.output_data_frame("penguins_df"), 
    "More items" 
)

def server(input, output, session):
    @render.data_frame  
    def penguins_df():
        return render.DataTable(penguins)  

app = App(app_ui, server)
```

![image](https://github.com/user-attachments/assets/b63188f4-38b4-4eba-aea8-7cc61cbd66b4)

```
pip list
Package            Version
------------------ -----------
anyio              4.4.0
appdirs            1.4.4
asgiref            3.8.1
asttokens          2.4.1
click              8.1.7
colorama           0.4.6
comm               0.2.2
decorator          5.1.1
executing          2.0.1
faicons            0.2.2
h11                0.14.0
htmltools          0.5.3
idna               3.7
ipython            8.18.0
ipywidgets         8.1.3
jedi               0.19.1
jupyter_core       5.7.2
jupyterlab_widgets 3.0.11
linkify-it-py      2.0.3
markdown-it-py     3.0.0
matplotlib-inline  0.1.7
mdit-py-plugins    0.4.1
mdurl              0.1.2
numpy              2.0.1
packaging          24.1
palmerpenguins     0.1.4
pandas             2.2.2
parso              0.8.4
patsy              0.5.6
pip                24.2
platformdirs       4.2.2
plotly             5.23.0
prompt-toolkit     3.0.36
pure_eval          0.2.3
Pygments           2.18.0
python-dateutil    2.9.0.post0
python-multipart   0.0.9
pytz               2024.1
pywin32            306
questionary        2.0.1
ridgeplot          0.1.25
scipy              1.14.0
setuptools         72.1.0
shiny              1.0.0.9000
shinywidgets       0.3.2
six                1.16.0
sniffio            1.3.1
stack-data         0.6.3
starlette          0.38.2
statsmodels        0.14.2
tenacity           9.0.0
traitlets          5.14.3
typing_extensions  4.12.2
tzdata             2024.1
uc-micro-py        1.0.3
uvicorn            0.30.4
watchfiles         0.22.0
wcwidth            0.2.13
websockets         12.0
widgetsnbextension 4.0.11
```

**Comment by sssingh** [comment]
I am having the same issue (though I am using express syntax). I believe its happening because server is sending incorrect MIME type when loading **data-frame.js** script. I see this error in chrome inspect console...
**_"Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec."_**

**Comment by jwijffels** [comment]
> I am having the same issue (though I am using express syntax). I believe its happening because server is sending incorrect MIME type when loading **data-frame.js** script. I see this error in chrome inspect console... **_"Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec."_**

Yes, indeed

![image](https://github.com/user-attachments/assets/6a47a3a4-1f39-4482-96ee-d93cacbef85c)

**Comment by sssingh** [comment]
I fact I believe issue is not only limited to dataframes, I tried using `ui.popoever` component and it did not work. This could be because  `web-component-min.js` is also not being loaded  properly (seen in error log), possible that many other component won't work.

But same code, if copied in playground (shinyapps.io) then it works perfectly which tells me it looks like shiny package being installed via pip and the one used shinyapps.io may differ.

Hoping someone could have a look at it. Can't use in my project, back to Streamlit for now again :(

**Comment by sssingh** [comment]
[env.txt](https://github.com/user-attachments/files/16612106/env.txt)
![error](https://github.com/user-attachments/assets/c404395c-c676-4ab4-8f3f-c55cdf45c78f)
![app](https://github.com/user-attachments/assets/fe4c0a45-716e-40c0-8027-5a1d3134e02f)

**Comment by cpsievert** [comment]
This issue smells like the result of [this odd bug with Python's `mimetype` module](https://bugs.python.org/issue43975), and unfortunately, it's not clear to me whether py-shiny can do much of anything to fix the issue. 

BTW, we've had other users confirm that [following the recommended fix](https://discord.com/channels/1109483223987277844/1261916035225882634/1263576462003277876) in that Python bugtracker does indeed fix PyShiny's request failures, and will likely fix any Python-based web app that serves JS files on your machine.

**Comment by jwijffels** [comment]
Yes, can confirm that this bug was on Windows 10 and that changing the `HKEY_CLASSES_ROOT\.js\Content Type` from 'text/plain' to 'application/javascript' fixed my issue as indicated at https://bugs.python.org/issue43975
The data frame also showed ok behind a Shiny Server and ShinyProxy which was running on Linux. 
Thanks for providing the links! I'll close the issue.

**Comment by jcheng5** [comment]
Given the severity of this issue, I think it's worth looking a little harder for a workaround.
