### ISSUE TITLE
Windows - "shiny run --reload" logs show strange characters

### ISSUE THREAD

**Issue by MadhulikaTanuboddi** [posit-dev/py-shiny#162]
Tried running a sample app on Windows after the necessary set up.

Noticed strange characters when running `shiny run --reload` command

<img width="1517" alt="Windows_PyShiny_reload" src="https://user-images.githubusercontent.com/5369655/168397149-ef383351-7cb1-4f00-802c-013dcc55b0eb.png">

Some online articles suggest to change the command prompts font type but that option did not work for me.

<img width="1252" alt="Screen Shot 2022-05-13 at 3 06 27 PM" src="https://user-images.githubusercontent.com/5369655/168397429-9390211a-9113-47e2-924a-125ee3e03396.png">

Ref: https://answers.microsoft.com/en-us/windows/forum/all/windows-10-command-prompt-issue/2974b24c-afe6-478c-91fb-5ac1757bfb48

OS: Windows 10 (I used Parallels Desktop VM)
Python: Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32

**Comment by daattali** [comment]
FYI I'm seeing the bad characters even in PowerShell on windows 
![image](https://github.com/posit-dev/py-shiny/assets/952340/9c91c19f-f2bd-40ae-a9b0-e02c55a59af4)

**Comment by gadenbuie** [comment]
The weird characters are [ANSI escape codes for colors](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors) that aren't supported by your terminal. The log messages themselves are emitted by [uvicorn](https://github.com/encode/uvicorn), so they aren't entirely under py-shiny's control.

But [uvicorn's deployment docs](https://github.com/encode/uvicorn/blob/40b99b8436c0c261e3a85d10e291424072946292/docs/deployment.md?plain=1#L85) list a `--no-use-colors` flag that can disable colorized logging. It's also very likely that the logging package used by uvicorn would support the [NO_COLOR environment variable](https://no-color.org/).

Unfortunately, I don't know if we pass flags from `shiny run` to `uvicorn` and I also don't know enough about Windows terminals to tell you how to set the `NO_COLOR` envvar, but hopeful this gives you or someone else on my team enough hints to figure out those last steps.
