### ISSUE TITLE
Access to the session: I want to store values there

### ISSUE THREAD

**Issue by vindevoy** [posit-dev/py-shiny#1653]
Is there a way to write and read values from the session ?  My own value, not an existing one

**Comment by schloerke** [comment]
@vindevoy 
* Are you trying to read/write values within a single user's session?
* Or are you trying to read/write values between all sessions within a single shiny process?
* Or are you trying to read/write values between all sessions within many shiny processes?

**Comment by schloerke** [comment]
If so...

> Are you trying to read/write values within a single user's session?

Variables within with `server` functions will be scoped to each user's session.

> Or are you trying to read/write values between all sessions within a single shiny process?

Variables outside the `server` function will be scoped to the shiny process.

> Or are you trying to read/write values between all sessions within many shiny processes?

I'd recommend using a data base connection as it'd need to possibly scale beyond a single machine.

For single machine: Maybe memcache?

For multiple machines: Maybe duckdb or mysql? Or Cassandra or MongoDB?

**Comment by vindevoy** [comment]
I would certainly like to know how to do it for a user's session.  That would be nice for permissions and so on.

The rest may also be useful, but I don't immediately see a use case for it.

Unfortunately, I could not find much information in the documention on how to use the session as datastorage.

**Comment by schloerke** [comment]
> Unfortunately, I could not find much information in the documention on how to use the session as datastorage.

I don't fully understand what you're trying to achieve. 😞 

If you're looking to see how you can set reactive calculations or values within a user's session, here is a demo: [shinylive link](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbDOAD1R04LFkw4xUxOmTERUAVzJ4mQiABM4dZfI4AdCPUatO3MRKkyhUQmQ4A3OPv06MXBWQD6LADYcNdAApdSGDlYIA5UKYABmUARmjYpgAmaIBKJwhMgAFVfwwSDX0NGiYyPjIAtMR9JjqVODJ5OggmGmCIACpksVEQN0UMCCqmTpSAX2DMgGImACU4a1sHJkIob0J5byhbUiYAdw4yEyYoJnkWTQByUUuRDlIcqxt7OAL1wmK4Up8-TQ81hsqjVWvUhE0WrJ3EMRmNkk9Fi8HLwaDQ4DYql9Sh5gbV6oIuJVggBlXz+VYfLY7B4QRBMKK-fwAj5VDJZCCzBZLV5MOzreRwA5HE5nC7XW7CFg0zKM-587wCpgAXga3OR8oFwEJTAAPkxwqQ4ABdAIGiBwNn6aazACqqDUO0Fsro+lyiOWb2+aIxbLdas9DnIAQGZCGbJKTBx1TxdWdHg1b0ulRDMLSlogfqRntR6Mq4e+kdxoLqBKDJLJml5-LgdIZFbo8errLA4yNQA)

Example of using a reactive value to display dynamic UI depending on the value (e.g. user is logged in/out): https://shiny.posit.co/py/components/outputs/ui/#create-dependent-controls

**Comment by vindevoy** [comment]
I don't have actual code for the moment that needs it.  I read that everything defined within the server() in reactive.values is stored for the user's session.

Guess I would solve most of my coding that way.

However, in that function I pass outputs and sessions, but how to use them ?

**Comment by schloerke** [comment]
Closing as there is no direct feature request or bug report
