### ISSUE TITLE
shinyTree in python

### ISSUE THREAD

**Issue by WorkLifeTalents** [posit-dev/py-shiny#1654]
Hi
Do you plan to add a similar shinyTree package python as we have in R. In fact, I'm looking for a feature to have nested group checkboxes. I would like to replicate the following R code in python: 

```r
library(shiny)
library(shinyTree)
server <- shinyServer(function(input, output, session) {  
  output$tree <- renderTree({ 
    list(  'I lorem impsum'= list( 
      'I.1 lorem impsum'   =  structure(list('I.1.1 lorem impsum'='1', 'I.1.2 lorem impsum'='2'),stselected=TRUE),  
      'I.2 lorem impsum'   =  structure(list('I.2.1 lorem impsum'='3'), stselected=TRUE))) 
  })
})
ui <- shinyUI(
  shiny::fluidPage(
    h4('Shiny hierarchical checkbox')
    ,shinyTree("tree", checkbox = TRUE)
  )
)
shinyApp(ui, server)
```

**Comment by gadenbuie** [comment]
We (the Shiny team) don't have plans to port shinyTree to Shiny for Python, but the maintainers of shinyTree might. I'd recommend that you follow up with them in their repo: https://github.com/shinyTree/shinyTree
