### ISSUE TITLE
Altair examples in docs broken in Safari

### ISSUE THREAD

**Issue by gschivley** [posit-dev/py-shiny#1680]
Looks like the Altair examples need to include height in the properties or they don't render correctly. I saw the explanation earlier but can't find it again. 

What current examples look like
![image](https://github.com/user-attachments/assets/87cd1b04-1612-43d2-ba7a-91ad76e22f9b)

How they look with the height set in properties
![image](https://github.com/user-attachments/assets/514d633b-d0e9-43c5-99a2-1f81609a6467)

Setting just width doesn't help
![image](https://github.com/user-attachments/assets/81c1cacf-6645-4cbd-88f4-4d140a7f7c31)

**Comment by cpsievert** [comment]
Are you on Safari? Seems like this issue, which should be fixed upstream in altair itself https://github.com/posit-dev/py-shinywidgets/issues/144

**Comment by gschivley** [comment]
Yes, on Safari. Even if it's an upstream issue with Altair, you might consider updating the documentation to have a height just so it renders properly. I'll close the issue though.
