### ISSUE TITLE
More breadcrumbs between examples and templates

### ISSUE THREAD

**Issue by nealrichardson** [posit-dev/py-shiny#1682]
I was looking for the example OpenAI chat app and couldn't find it. https://github.com/posit-dev/py-shiny/blob/main/examples/chat/playground/app.py#L6 even says it should be there. Looking at git history, I discovered that it was moved to the templates inside the package. 

As a user, it's not obvious what the difference between examples and templates are. (Is there one?) It would be nice to have more "see also" comments in the examples and templates--maybe that's only an issue for the chat ones because the other examples are self-contained and don't need to reference each other. At a minimum it would be good to update the code comments to point to the right place. 

Related: https://github.com/posit-dev/py-shiny/issues/1671

**Comment by gadenbuie** [comment]
For context, examples live only in the repo and aren't bundled in the package; the templates on the other hand are part of the `shiny` package and are available via `shiny create`, which now includes a "Generative AI templates..." menu item (happened in #1631).

With the latest version of shiny, you can now run the following to get started with the OpenAI chat app

```bash
shiny create --template chat-ai-openai
```
