### ISSUE TITLE
Adding attributes to inputs

### ISSUE THREAD

**Issue by thohan88** [posit-dev/py-shiny#1730]
There may be an easy way of doing this, but all my attempts to add attributes to an input using `input_xxx()` has failed.

My use case is adding [bootstrap validation](https://getbootstrap.com/docs/5.3/forms/validation/) by setting the `required` attribute. It would be nice if something like this could work:
```python
ui.input_text("id", "label", {"required":True})
# TypeError: Invalid type for attribute: <class 'dict'>.
```
I guess it would not be clear whether such attributes applies to the `<form>`, `<label>` or `<input>` tag, so I'm not really sure what a good api looks like here. This is an okay workaround for simple inputs, but more cumbersome for complex inputs (e.g `input_select`). 
```python
ui.tags.input(
  id = "id", 
  label = "label",
  type = "text",
  required = True
).get_html_string
# <input id="id" label="label" type="text" required=""/>
```
I also believe this workaround requires you to use `resolve_id(id)` manually to make it work in modules?

**Comment by cpsievert** [comment]
Most inputs and other UI should return either a `ui.Tag` or `ui.TagList`. In the former case, you can mutate the attributes via `.attrs`:

```python
>>> from shiny.ui import div
>>> x = div()
>>> x.attrs["foo"] = "bar"
>>> x
<div foo="bar"></div>
```

In the latter case, you'll want to iterate over the list, and update `ui.Tag`s as needed.


> I also believe this workaround requires you to use `resolve_id(id)` manually to make it work in modules?

Yep, if you're encoding `id`s in HTML directly for a Shiny binding, `resolve_id(id)` is needed for module support

**Comment by thohan88** [comment]
Thanks for the response, @cpsievert.

It does not solve the example above as it adds the attribute to the outer `<div>`-tag in the case of a shiny input. Is there any way to add the attribute to a child tag this way? 

```python
inp = ui.input_text("user_input", "Enter text:", placeholder="Type something...")
inp.attrs["required"] = True
inp.get_html_string
#<div class="form-group shiny-input-container" required="">
#<label class="control-label" id="user_input-label" for="user_input">Enter text:</label>
#<input id="user_input" type="text" class="shiny-input-text form-control" value="" placeholder="Type something..." autocomplete="off"/>
#</div>
```

**Comment by cpsievert** [comment]
Yes, tags have a `.children` attribute:

```python
inp.children[1].attrs["required"] = True
```

**Comment by thohan88** [comment]
Thanks @cpsievert, I should have caught that. 

For anyone else wondering how to implement input validation with this, here is an [example on shinylive.io](https://shinylive.io/py/app/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMAgujxMArhwl04UQmQ4A3OLMoATOHQA6EPQCsWTALxMdYC1YgbihSfHIYoGjQFFV5ADIcWFCNoAFADkACIA8gCyAMKk-mRexC5wGsESNJIQihykgQCUTCB6TCVMtvaOZBgA5nBkbgA2cJUAQtgAkhohDcTVXADKkgBGMBxkwXnOrh6UCb7+QcGEDRyEANZpTBlZSrlwnmQFRRClp0zKUHRbgsxm5Q6zNXWNzbNtnd29XABiNxMA3MUziUgcCODQmIEaDcMIQ2HB1gA1KArDRjbD5I6g4GlfqcbgYFh1doQVCSMjIhqSOCfPoQQYjMabMh0al5QEnHEAXyYcAaRMK2Jx1zoMFhDSgLBYPj8Uy6wQA7pKALQXVFQCipdlC0pc7Fc7UQA0cqyWSz6C1aCEuDQAfS4ZLItrVHA0GpyEECDvJtr5r3IEngUqgtTyiGx3qdfsqsM4DQ0cggwAAjABdZxkFksYAWOQAR2kcg0FlTpiYABVWXAI6SfdHHnCOPHE850JpAtIMGjlIEgywQ2omMtJSxbSYLFwXRplTQ4Ckhgo1hY8nk9GuIJHfTAoE2y53NxQAB5kL0acdgZo7hoWCQSoZ889ubdN8P4JhQcl2RioJoUc+Xptlz0TcAIaWMmwTSgU3TDUsxzMAyGwVBqzAUszAsUDrE3VARwVQQND3DgMGw3D8NPc8cKlPC6GLN87wfCwAAVSJo19V2gVx7VrJ0p3dXISKo-CJCYppJTgJhUAYZRXXEqAJJY2j2JtLjHWdFFXT4z0QOfBphLARjRIFSTiGkrR33OdSCLgZUdKAi00FQW1pEIrAB1tD8yGIQJsU7eEXFtEhyFmbzOWBTsyBDFgMCUMgmm8sAACl+iYElHQs9Vdn0MA8jwHUSnCyLCUIOgOFQE8jHY4Ucp8ojuxC4VOzqvKzl8gBmeLEjpZdctC4UpCIiLqii6FRXqvqwW4rcrx68aJtUyiWGojQZtm0590mhRMttIZyU8z0LB6OkGVGMgb3MMBOq4M6FVdMg2HPZMAAZHoAUjO4cpTHc6hjICBlUkvhLmwbrmuFV1z0On4bhvUGcQ+0dzwCFIWFVSzNJh3rVogEy0b-StqRW8bqsxnFO2IclVKPHjtAXJQYHiuQWEkBonSpkGSeBeHbTLCwhmqZUVmqNhhFQZUABYmCGfDtCYBhMi0adWusKrCbOLnz2nGgmkPJgDEkPxwWwZVAviY3Zhl9Tqj+sZmhRwhzauZQ2GVJ7Hox05ifY9crVYbRVDoL1uIkcmyEdCQiSlD0w3XU5GeZ4QzDkTaVDgDA1WpfIY9KAABJPslUDA4BoWdFGxXP5Hz1P9mCyMMEh+lhhOyrSh9218nDDneAhWv6+OsZ8l4Yx8bgDvVrjlnCTqKELAATXJ3kgqLRBClr0D8j1bKs5KbOQ8dMvEy0OhorgY9sR98fWZPk9o87uQyEkOgTgvzOLT0ByyzEVBAgcpyZF9uh-bsTAFyVMQA).

![Image](https://github.com/user-attachments/assets/a76aeb86-4113-4bc8-b0f8-a0a79461bb3f)
