### ISSUE TITLE
Row names for render.data_frame

### ISSUE THREAD

**Issue by cmfield** [posit-dev/py-shiny#1775]
I don't think it's currently possible to show row names (or the index column names in pandas terms).
If there's a way to do it, please let me know, otherwise I guess this is a feature request!

**Comment by GiorgioMiglia** [comment]
You could simply add them as the first column of the dataframe. For pandas:

```python
df.reset_index()
```
[Shinylive example](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMAgujxM6lACZw6EgK4cAOhD4ChTVFAjSoLJvq3TVqgMRMAwlKgUmZAO7FWsVABs4TACK2oAMTpYOBZVPTIoJgBeJhBVJnimAHIAOSDExCZgRJE3DkI4RIlEgCFiACNCpMs2KDpcgqKfADcOaUSAXTw4hOyAcwKM4AAmAFYJAGYABgmxpiGADk7u+MTLDjJsdMyUuAcmAE1BAGtKxIAZUmlSU4AFWo4WU4AVYiPsYg7VAF9QmijjDA+cIBIIACjCUAAlKZoOgAPpKf5KLBQfpwmhuJTSUHLJjItxQd4KMhwkiYmAQFg4iAJWl4jgYQi1bG4ukJZFMujSOFsOBQWR0HFgIH+QLwJgOdZsYjEpgASV0cAAHsowJCujS2XTkTKyKhiXCIeixXAhdIaHDJWRpQauLIVWrWQl1U74hzmdStdqGZzubz+XIhSKQeKrWx5YqHS7NV63QzdfqSUb6GDVebLVK4XblaroTG6dGve6uZ7Y3HGcyeXyBUHfCHPGGI-amABaKwKFhkRhMMlMaDwaFqjVl8sJg3Jk1mi1hrOR0kdrswXOupiF52qPOhOB-FhyJqBriJiRjsgSXcsFgcUiQxC4gACJ-vUkVdAwE6CuNkf3TYd1s-toI3iuUhkAodA0s+AqAr4ADidCtOCNB5rS96Pvmd6QXIb6+MaH75l+TA-pm2ZKoBt75rSIFgRBMhYSKcEIeaGBSLuJIkYBm7oWhtIYbRr7vvAn7boR07EXOhALowZHAXAoHgZIfHQeEDHYhCkRMSxsn-sqoL9sEkSqpYkkwKkglqpxqhoKg-xiKgoJWQiHBnnuch5mAXx4OAenUFIACOShSPA5AsBgZBKmQ+BEKQFBUMg2i6Poqjue0QA)

**Comment by cmfield** [comment]
This works, I suppose I can format them to look like the column headers - thanks.
