### ISSUE TITLE
Style ui.chat

### ISSUE THREAD

**Issue by DvGils** [posit-dev/py-shiny#1804]
Hi!

Currently, `ui.chat` will not accept a `style` kwarg and will throw this error:
```
SyntaxError: keyword argument repeated: style
```

It would be nice if had an easy way to style the chat interface, changing the font, assistant icon, etc.

**Comment by cpsievert** [comment]
`ui.chat` doesn't exist -- `ui.chat_ui()` does and allows for a `style` parameter. Looks like you've supplied 2 of them?

**Comment by DvGils** [comment]
Thank you for your reply. As it turns out, I am an idiot.
