### ISSUE TITLE
Changing themes on created app

### ISSUE THREAD

**Issue by sprenkamp** [posit-dev/py-shiny#296]
Heya,

thanks for making this possible. I just started a new dashboarding project and decided to give py-shiny a go.

On question that came up is how to change the style of the created app?

In R this was done over the theme parameter within fluid page e.g. fluidPage(theme = shinytheme("cerulean")). I checked in https://github.com/rstudio/py-shiny/blob/main/shiny/ui/_page.py but cannot find the theme parameter. Is there currently a way to change the style of an application?

**Comment by jcheng5** [comment]
It is currently hardcoded but near the top of the list in terms of priorities IMHO.

**Comment by cpsievert** [comment]
Hi there, you might be interested in https://posit-dev.github.io/py-shinyswatch/ and/or the new [`ui.Theme()` API](https://posit-dev.github.io/py-shiny/docs/api/core/ui.Theme.html#shiny.ui.Theme)
