### ISSUE TITLE
Disambiguate /examples from /shiny/examples

### ISSUE THREAD

**Issue by nealrichardson** [posit-dev/py-shiny#520]
When writing apps, I found the examples to be a great resource for finding the right snippet to insert into my code. But more than once I got confused because there are two directories in the project called "examples": one has the full app examples, the other has the examples for each element for the API docs. Can we rename one or both to make it clear what's inside?

**Comment by gshotwell** [comment]
This has been disambiguated (shiny/examples is now shiny/api-examples).
