### ISSUE TITLE
Multiple occurrences disappear in selectize

### ISSUE THREAD

**Issue by NicolasConrath** [posit-dev/py-shiny#655]
There seem to be a bug with shiny selectize when the user enters a string of mutliple words with common letters : part of the words or even whole words disappear in the proposed inputs.

Here's a small example, try typing "letters letters" in the following selectize input

 `
    ui.input_selectize(
        "id",
        "try typing several words",
        ['',
         'letters letters example',
         'look letters disapear !'
        ]
    )
`

You can also try that one where you can see that even if the words have one letter in common the weird behaviour occurs

`
    ui.input_selectize(
        "id",
        "try typing several words",
        ['',
         'king of kingdom',
         'king of internet',
         'king of galaxy'
        ]
    )
`

**Comment by GShotwell** [comment]
Good catch and a very odd bug.

To reproduce on [shinylive](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMAgujxM6lACZw6EgK4cAOhFVpUAfSVMAvEyVYoAcziaaAGyXSAFKqYODHDF1QKymlnAtxCZDgBecDZMymAc0mESYWR0PGTYqFzGrHAAbnJQFkwA7oLSLFFMwADkJRIlPmQUdCxMVTV1cAAesKg+5UyVxMQA1vVw1XJ10hwsaHBQdEwAhCVMALpMAJSqq2rQ6Hqi6DYa2hwSAHKkcOtgAL4LQA), type "let let" then backspace out, selectize drops letters and doesn't reset when you clear the search term.

**Comment by gadenbuie** [comment]
I think this is common to Shiny for Python and R, I can reproduce with this small app:

```r
library(shiny)

ui <- fluidPage(
  selectInput("id", "words", c("", "letters letters example", "look letters disappear"))
)

shinyApp(ui, function(...) {} )
```

Interestingly, it only affects the label, the selected value is correct but it's probably a bug in how the selection highlighting is being cleared.

**Comment by GShotwell** [comment]
Thanks for the reproduction, weird that nobody has reported this on the R side.

**Comment by cpsievert** [comment]
Appears as though updating selectize.js v0.15.2 (as we're hoping to do in R via https://github.com/rstudio/shiny/pull/3875) fixes this issue. Unfortunately, we probably won't actually upgrade in R until [this new regression](https://github.com/selectize/selectize.js/issues/2032) gets addressed, but if this is urgent for Python, you might consider working around that issue by enabling the `remove_button` plugin (which IMO provides a better default experience anyway). Here's how you can opt-into that plugin in R

```r
library(shiny)

ui <- fluidPage(
    selectizeInput(
        "id", "words", c("", "letters letters example", "look letters disappear"), 
        multiple = TRUE, options = list(plugins = "remove_button")
    )
)

shinyApp(ui, function(...) {} )
```

**Comment by cpsievert** [comment]
This should be fixed now (in the development version) thanks to https://github.com/posit-dev/py-shiny/pull/819
