### ISSUE TITLE
Rename accordion methods

### ISSUE THREAD

**Issue by schloerke** [posit-dev/py-shiny#730]
None of the other methods have verbs at the end. To make the names consistent, I propose:

Accordion methods:
* `accordion()`
* `accordion_panel()`
* `accordion_panel_close()`
* `accordion_panel_open()`
* `accordion_panel_insert()`
* `accordion_panel_remove()`
* `accordion_panel_set()`
* `update_accordion_panel()`

| From | To | Comment |
|--|--|--|
| `accordion_panel_close()` | `update_accordion_panel(open = False)` | |
| `accordion_panel_open()` | `update_accordion_panel(open = True)` | |
| `accordion_panel_set()` | `update_accordion(open=)` | |
| `update_accordion_panel()` | `update_accordion()` | (Drop `_panel()` as it's really updating the accordion, not a single accordion panel |
| NA | `toggle_accordion(values = Union[list[str], None])` | If `values=None`, toggles all accordion panels. Otherwise, toggle the specified panels |

No adjustments to `accordion_panel_insert()` or `accordion_panel_remove()`

------------------------

cc @cpsievert @gadenbuie

**Comment by gadenbuie** [comment]
I wrote up my thoughts in [rstudio/bslib#706](https://github.com/rstudio/bslib/issues/706) where I'm also in agreement with `update_accordion_panel()`.

**Comment by cpsievert** [comment]
I would be open to trying to fit everything as verb first.
