### ISSUE TITLE
Reactive problem when using ui.panel_conditional

### ISSUE THREAD

**Issue by Jujuke** [posit-dev/py-shiny#734]
In some situations, when a ui.panel_conditional has its condition verified, it will trigger unwanted reactivity.

Here is an example :

```
#!/usr/bin/env python3
import time
from pathlib import Path

from shiny import App, render, ui, reactive

app_ui = ui.page_fluid(
    ui.input_radio_buttons("command_choice", "Choose a command", choices=["Option 1", "Option 2"]),

    ui.input_action_button("compute_button", "COMPUTE"),

    ui.panel_conditional(
        "input.command_choice == 'Option 1'",
        ui.output_text("output_text_1")),

    ui.panel_conditional(
        "input.command_choice == 'Option 2'",
        ui.output_text("output_text_2")),
)


def server(input, output, session):

    @output
    @render.text
    @reactive.event(input.compute_button)
    def output_text_1():
        if input.command_choice() == "Option 1":
            message = ui.modal(
                ui.HTML(
                    'output_text_1 is loading...'),
                footer=None,
                easy_close=False,
                fade=True
            )
            ui.modal_show(message)
            time.sleep(2)
            ui.modal_remove()
            return "Result from option 1"

    @output
    @render.text
    @reactive.event(input.compute_button)
    def output_text_2():
        if input.command_choice() == "Option 2":
            message = ui.modal(
                ui.HTML(
                    'output_text_2 is loading...'),
                footer=None,
                easy_close=False,
                fade=True
            )
            ui.modal_show(message)
            time.sleep(2)
            ui.modal_remove()
            return "Result from option 2"

www_dir = Path(__file__).parent / "www"
app = App(app_ui, server, static_assets=www_dir)
```

In this small example, if you click once on the COMPUTE button, then change the radio button selection, you will see that it executes the two `output_text` functions. This is not expected as both functions have a `@reactive.event(input.compute_button)` decorator.

**Comment by jcheng5** [comment]
Ah, I can explain this. You're seeing the interaction of `conditional_panel` with Shiny's default behavior with outputs, which is to hold off on executing/rendering them until they are in view (we call this "suspend when hidden"). When the compute button is clicked, both outputs "invalidate", meaning, they know they need to execute. However, only the visible one actually executes at that moment; `output_text_2` waits until it's visible. But by the time it's visible, `input.command_choice()` has changed, so it proceeds with execution.

There are probably several ways to solve this problem, but without knowing more about what your actual app is trying to do, the simplest I can recommend is to simply disable the "suspend when hidden" feature for these two outputs if that makes it easier to reason about them. You can do this by changing each of their `@output` decorators to `@output(suspend_when_hidden=False)`.

**Comment by Jujuke** [comment]
Thank you so much!
With your answer in mind, I went digging into the code of the output class and saw that there is also a `priority` parameter. 
I feel that both those parameters are major ways of managing the reactivity and should appear prominently in the documentation.

**Comment by gshotwell** [comment]
That's a good callout, I'm going to close this issue but we should have an article about priority of execution.
