### ISSUE TITLE
Alias reactive.Calc and reactive.Effect

### ISSUE THREAD

**Issue by gshotwell** [posit-dev/py-shiny#736]
From the conference workshop, users find it confusing that `@reactive.Calc` and `@reactive.Effect` are capitalized while the other decorators are not. The naming makes sense if you know something about the naming convention of python objects as well as the internals of how those functions are implemented, but many users don't know that. We can probably create `reactive.calc` and `reactive.effect` aliases without causing a namespace conflict which would smooth over some early user bugs.

**Comment by wch** [comment]
This was implemented in #822.
