### ISSUE TITLE
Deselect or clear selected rows in Datagrid

### ISSUE THREAD

**Issue by ottomorris** [posit-dev/py-shiny#743]
Hi, 
Loving shiny for python and the new interactive tables!

In your example:
https://shinylive.io/py/examples/#data-frame-grid

I noticed that you can only deselect rows when selection is "multiple", not when "single". Would it be possible to update so we can deselect rows even when using single?

On a related note, is there a way to programatically update selected rows e.g. if I want to sync two tables so that the equivalent rows are selected when I select a row in one of the tables?

Thanks for your help!

**Comment by schloerke** [comment]
Added `<DataFrame>.update_cell_selection()` in #1248 

Closing

**Comment by schloerke** [comment]
Workaround for unselecting a row with `selection_mode="row"` (previously `"single"`)... Hold `cmd` (or `ctrl` for non-Mac) and click on the cell

Thank you @ottomorris for the detailed issue!
