### ISSUE TITLE
Create outputs programmatically or at runtime

### ISSUE THREAD

**Issue by uzpaka** [posit-dev/py-shiny#752]
Hello,

In R I can create outputs with string ids like this:

```
setup_output <- function(chart_id){ 
  output[[paste0("chart_", chart_id)]] <- renderUI({
    return(some_function(chart_id))
  })
}
```

and then call setup_output("1"), setup_output("2") etc. in a loop.

How could I do that in Python? Not only for outputs but also for reactives and observers?

**Comment by jcheng5** [comment]
Hi @uzpaka, it's much the same in Shiny for Python. You can pass an `id` parameter to `@output` if you want to use a dynamic name; if you do that, then the function name is ignored.

```python
def setup_output(chart_id):
    @output(id=f"chart_{chart_id}")
    @render.ui
    def _():
        return some_function(chart_id)
```

Reactives and observers don't need to be uniquely named beyond their local scope, so you can just create them as you normally would--no need for dynamic naming.

(But also, this is made so much easier if you use modules instead...)

**Comment by uzpaka** [comment]
This is great, thanks!
