### ISSUE TITLE
How to add a CSS spinner

### ISSUE THREAD

**Issue by gshotwell** [posit-dev/py-shiny#762]
We don't currently have a great loading indicator when long-running computations cause components to take a long time to run. A user asked for a simple CSS spinner similar to [shinyloaders](https://github.com/daattali/shinycssloaders), and we put together [a simple example](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMAkhFQBXMizxMA8lMnTZAZTgsWHUrICC6WXThRCZDgDc4BygBM4dKwEdZEjgB0IfAUKan47+oxMqFBkbAA2HABGvPyCwgAKIWzunnFBUBDWUCxM2UHWKbHeEBL8PHnihV7C2dgQhFruTZlwNEwA7hyhAPosqFwQdgAUAFRQdADmLACUiO5MC0yGZBJ0EEwuGNbmQ-OL+yCuRGHZLEeITEd9A3YAtO10aKh2RwC+eHv7C2OTMp9fm22ZiGh2Op3OlzA1wggzob2m-wREGaT26LiYAF4NhwsFAJnBujQwi5rLt1otNlxCMTbN1CBoholQkNuoSOGECd1prjDOQmAB6SEsMghDiEfnQ2EYelnMDTD7khaU8RSXoRWx0XZgBjtWWyI4AJWIuqOsgADLIAIxmi1MABMZvl-06PUlw02xEUqqyIsJj3gWsMLAkYTIR2mTsVTAAxNiMJ6yEpuj6oH7YHBA+oQ2Q7eGFUjmrY2iw7BZNVwlBcxEoZEwE5X5F7lKx1JpSBc1BotBBZv8AAL1qT93karYhVP0dP-Wr1JhFpZZ0NDXtR-ZQdpQLq5Fh1BrEDAsDlwVBDO1Ir6LZardaoawYAAi44AYv6M-8LwtxBhHplGN+Mts5BDLa1q2poABecAYkMFZSN+xosMusgACwRrIJDEjAEAsBiETClqOgAEIAML3uG76LAWUYDk2w42HYY6+pOfhRjOhBzq0C7BqGdrLnMq6XnAKxrPkD7Pq+ZIfl8X4-tYf6yVwZDAVaNqyBBUEwSqZDwbqSFMKh8pMBhpTYbhHD4UcRGkeRAkLFR7hPJiTB6CeqIuGppZ2EiYDvOA0DwNQwqiuKbp0NKGj4EQpAUFQyAHv0MJ3A8Tx2EwhxRgImimO2C4nKYFgANz7O4rzNPFNx0Gl-yZV03YXFAkQsMQxIUAV-wcjQZAXGabVRnQHATGwXVMD1-xkMQqDdb1+yRMQZDjTAU3-DA4wTFw9VSMQvWlciED8iMTBqByJhMOViWVRwbRQKwUQRBAEy8Dk35wIQUBhIQIaivdTAjPy7jPa972faY30AH6naFCzpTNggahcloAGyoAAHqwzUcNYMY0AAzDjOPTYss10BqtyPNsEgsBcACsZoAKQEwsRMk+Nk1MIjKNo+qMbY8hACcAAc1iRAzHQY6E8MOijItsHAA1DRLZpS-89xwJEADWXS3BkfCijl0L2jkd1GBdEA0FwXRwCL+2HVANDjBwP1-axHgrdlEAXPrdqG1wxu8Kb5utf84G3FwtjI-DNqjRAO3NNbKi2-bjvuH2Kvq5ratwNgzHqKwCVVVGdP51Jqca2QtxkD+LA0IIi1LHNIQZmatgTNMIsx1GoG00XH4l5rFcZFXNcXAwIoUEM2MI03cAt23JXNH2GdZ6+OT69DiyF2vF799h1d0LXI8N8Bzet-87f7J33db5Xu-7-XY8T1PM+nyVPkALpAA) of how to get this sort of behaviour. 

The basic pattern is to define a function which wraps children in a div, and then use CSS to add a spinner when that class is `recalculating`.

**Comment by stephenwilliams22** [comment]
@gshotwell Thanks for adding this example. However, when I add this spinner to an interactive plot, https://shiny.posit.co/py/docs/outputs.html#interactive-plots-1 for example, it seems to completely interfere with the interactivity of the plot. For example hovering gives no information in the plotly plot. Same with altair. Do you have suggestions on how to update this to not interfere  with interactive plots?

**Comment by iainmwallace** [comment]
It also interferes with click events on a table

**Comment by iainwallacebms** [comment]
In case it is helpful, I have created an example that shows this issue [here](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAYgAIA5YixOgFQAsBLAZzrVR0Arjzh8odACZwAbnAA2xVPHJ05AJx5dSdYgDM6qRWQhcIcDAB0I1rjFTF1ZOgCsepa3vXEYhqGQ55LgAjOjsHJzoABX8OW3tHZygebAhCbWtM0wTImH8jZiDgrGwCpL4jMniI51QoCElk-grJT29fHm4IbDCc5wBBdDw6dUppdWGhLjxRqEIyLjksmDJCKE06AF5DSQxZyQB9Qh4ZAAoYgNODg70ueThrgEosdcpnAHo6SzAVtc0MY4yb6Pay-dY8DCSbyoU7Ab6SXiob7Db4cJH4L5gKH+ZGYgCOokIuO+Mh4xLAAHM4OtyX9gt8ALrDKAAD14mwAjMMzEY5nBNmx1EI4CCbA04AYAO5cAIHHioMzmdSnABU6wpPEeiGsdF1IzgZCE6ggwi4kMWpx1eutIG+hHkyTJSEx8sVcHUAFpJeoBO7vgBfPBW626tXqDVBk0h3VTc1nW1EB08J2sb6uiBKgOi62i6wCA5TLaml5Um7yKaSS1RmNmsz2oTSI7J86xK43O4PA7POqjVSfNNkfxcQjvdNKgHJ4GR62xjjUw4kchvKvRmsYQcajA8MjYe4r1fW75HsDBkPvFV0ADKeXk93UdD0pGcj-vqFGL7yZAokjoFBZzhVd5T2tN84GGQdgnudcoEguA6FtatV0fcgPS0AAvOBWB4G87wAbmAvV-SyA9QPAmCoIg+54II6NkLIVCuAwrCcPdfDEOtIj2L1Y8jy43Vsz1R5pz1WNvElfdo1jEhyxgCAJIPOgABZhIU4s6nMeQDklBR5Hk1S1x5IQyAOH0EWIA5giMshSB4PT9MPMAygOHdUDgckomMX9SjcjE4R+fJjCKckylMcxGRohSBNUoSIpivji2koRZLs6MAA4VIU6VZTHd1TljYgjNQIyDjKS1HOMDlcXtYcAGsBSFMCpEg6rCDqwVhWGDhiA0eqOroYIhU6XqRTig9RsEjLROIcSIqk4gZLkgBmSYzQKsgiuMv9jI0YIhxgMqWpqg4zEfYFxsks1EuS5bizWjbnLgf8Dh2vayskZqgla46IFOsBHnOkM5oW04bvywriq2573V2hZ9tRbr3W+37-oymdLvmpKlpWjA7ohx7tuh17vgGkQOCR4gzoyuLczFaQDFEdQNFOQyyGGXHWboURk20CAtWI7jENPAABdnhd7cYsGMU4oHkMhNm+fpObWL93TKYFT2SVJCCkCVDAq04+fiqBJSgGVmi17Qt3uOAYQAJiikMuAMFnJeYZzvINrZtm+T8yiCpAIutW4KWZFki0qLchGCMpbIdkjZfXGU92+ABxYhiB-eafzBTR1fi61WS3ZWKGVHOeD8yUqjAJk6DLvz7ApRk49XUZDWNB8uEbsUDwUJ2wggDbXc2j3Hi9zEQrMHztXzvUvB8PXmFCuDwkSfgxGGKkfBK4gzA5ikKTKDeKQWMh7n51TBG2FKFP30qy+ZMQysr8kG7OwPVwAajoTeYG33eDfftGL++8T7JzAGnDOuh5DZ1WOCPO9kab2VbkaE0SJu56hFuDKoiEhbi3dOufGADEJ0zoIdcmBtp4HmQe3O0n0arakyGAOgX83CkEhElVAtkXZlA5EcOhBtuTinIJse2586CYPWkZMWYx8FbSIdaEh715BkJOsQChEVqEmnhB9WqDCbBMJYe4CA7D7BcIHkZIevClGHQEf3aQwjRHoN1BIja0jxTqAIf+eReoSFdQ0OQw2VCDQoMxH490ejvjMNcEYkxnDmbmLIJYg4YTlRCTsW8ERiCMGixwXgjxciHYkJJp0AJlCW7BJoWAYpHAIkGOiWwyQHCzGDx4RZQaHBbFmHsXLRxWQBBFkGDCfMUxhgMw0MMaQlkKTDVFGAQM4BoDwGoGXCcMh8BECfG8agPsM4KGRD7VAjd8B2l3PsrEiIzlojOdiKuQYwDP2OWAAkcAiSPNJGc2AZyqQ0keXSXi3wACyUA0KNDoAAJQABqKWRLbLkAA2PAHI4UAAZEUclRYtDAABOPAtsMBwttoiuFGBFIItRVyZS0L9FApBRISFik6AAHUoBHNxfCol5L0V4ExTivFqUADsABWRF-KMDIsJeSvAlLGEABF-A8CECafl6KYV8qlYi5F6UsXLUxalYVeLFqEo5KlfFXIzXqsqvogAEo4cwzgGUyvUIsHybKSV4ARbbQV6UORcsxZq7lGBYXCo5FiklykuQYsRYwm1xoDRXhqDBNayJjUYH5XgdKi0UUiuFZijkOaw0irFRKvAkbbaMIAGoyy4PUW5Kb2W209Rq-VqaEWYtJbi5FgajUlu5VG-RMqRAlzoJm5FybFIYGWhmrNttFL5thQGwVaa80YFSspVFkaqWAvdNrGdyKZUwvHZSxFpLU3usJZiuFOLc28slai5SZbqXbroLbRao78ANpXRaxSnatX5qxeejAebcV4pxRG9VD6t3qB3alN9iLQ2EoRUi0ViGX0Bv-QGxS4aTXLTA9Kx9UHn0wYAMLJtFelRDcLkOItQzygDmHEUmtAz2vDkHtazuRZeAAosm4lyl0q2yFZ+41GKxVpvHcipdoq109p1YwgFT72OXgADKkYnem3FgnvUwYDRJgN-KcNUfXb2xacmFOCo40pkj+Bl2Ev45phjIndOYv5VpntkaTP6KI1ABEt45h0AAGLWzIJKdOrRrOdr41K-lhLbbIubdqvAgrA3BtFVi9KRnlqbrAEpus80TREafJPcgMtk0RfU6S1FQbe1JcUjOwtqVi0bsYURjg6hsA8DvHQAAkvYd01b5BjtPelTDlXX0BtQ0lxas7C21bc72rL-nq3OA5LbVKyJDVuuUi509cKEXif44GuDJKl2IotdG0goKiOLGHOtsrW2ktpsFYS8dCWOSmuDSap7p2KW4sYWwYg2BmASAK94Xz62eXquVYB91wrx0NsRSuxawbQ1MZ+5a74-3AeDjoCD0gUAYVvdh9RztXIsVpuc7iklcL9WduReayN6OwAyozlSHHHAZb3AgFSdQyakvCozcaxF5nKf8tbRgL7SKV1poy79-R-QAVEboAAKSgHIII+iheHYzci8Nwvc35sUkjwty0ZcQbAF5vI3g6AAC1VvJsxZO7lwuZ35v0wG1dmvFJgaa-oqIhW-OLdGMELg6gwtHds1K5F5KhU6YzSu6bHJRVxbm8tM3i3-B0AhRyD0WKYWisy3gflOLdtSrFd67FRuU2o7O77xwPBCBzjoFijkikPRlvfXt4nanm+l8N5TlvRLT2Sv1YwpTzARB0E40aJQ+P8Cvs23gLFSWzUch1ampd4vV+D+ryP-R-nHA-hiEuH0dAVPWaS+lDNgquS2zhZSrtAbE-HvFz2rksPGH+fdD6J1dAZVmAptZqGmmohgnjHhejFuvprsKsPu6nJskO6EOHQAAEKOCz5C7qavpciLRG6YqCrKS4FLrjpkqnb84VrzQyDEB0At62zcbvpvZHorZmrIo4rjo+oi5ab4rfbgbWBzJ4ALKwAIDIDbhDgjg5QeLHA8DrKLgUBUDIBbgKgZjuheg+joDujUSIQOBaALCkCsCjAOgLByC4SHgQCcTWDyFuj3gIQgTEBaE8ysAwTuDlgUBsTWj3B6BkCsDIouF6hOoUgcAeF0BeGnjWSoCeHeG6jBDMDWQwBhGniW4UhmD2FGTEBsSmEQDnhXgKAvLODmGKH3h9wSBaCQRmAUhhB8B7AvIyyEBCD6ElF0CARmGjBrDKI1FDhc50AAB+dAuRSouoVheokRoe4SVBcKqAYcjhXAP4NAegi0MxMx4R-UB+ShpkXAIgrA5mAApAsYMeMB6CEawEimMZzPNJMXQDQFNmlu9AsdKJIAEAcbFmMQsXOJ3P4fccio8aeF6HAMEDVDKB6PUHYEODoZzAoc+nwOrtSPkT9GYDKHAAsRkZeFAHoOsFwPUUBIhACZ+HYSCWYGCXQBCesP3LcKYM4aeGhB6F0o9AcVHkESYVkBgBAMwKcBUc0dUbUVzqPF0T0Wof0bqAiPKA6NgKwIyeYKkVkNYAiUiSiWidYELF8T8X8TVHANgF4AIXwOmOodaMihsZqauPKb8fRGQD6BADwB+LoUDhQKcMitIBSI8AsWkdaOitqbqdGPqX8UafUKaY4DESMBaXACDCijaXaaeJxGkULEqSqT6PAOqaCbyYETqXGdaB6SaWab6YOJadaXALafaWIk6QmRFMmV6eoD6d4Omf6SOkGTmSYXMgyEAA)

Two issues with this approach are:
1. The spinner is only displayed when a selection is made
2. The plot is not interactive anymore

Per a suggestion, I added an additional css snippet for not recalculating but unfortunately that didn't help

**Comment by cpsievert** [comment]
We now have spinners by default, and you can customize them via [`ui.busy_indicators.options()`](https://shiny.posit.co/py/api/express/express.ui.busy_indicators.options.html)
