### ISSUE TITLE
Option `--reload_dirs` have no effect

### ISSUE THREAD

**Issue by bryan-brancotte** [posit-dev/py-shiny#765]
Hi,

When looking at `reload_dirs` variable, I think that the value provided by the user is not used : `setup_hot_reload` is called without `reload_dirs` [here](https://github.com/posit-dev/py-shiny/blob/main/shiny/_main.py#L283), and a few line later, reload_dirs is defined to an empty list at https://github.com/posit-dev/py-shiny/blob/54101ac4cdc38dec74a34a5e618f79316e1041d3/shiny/_main.py#L287

Thanks for your time

**Comment by jcheng5** [comment]
You're right, looks like there was a bad merge here. @gshotwell can you please look at this as part of the overall uvicorn options PR?
