### ISSUE TITLE
Append bootstrap class to ui.output_text

### ISSUE THREAD

**Issue by stephenwilliams22** [posit-dev/py-shiny#803]
In a simple example such as https://shinylive.io/py/examples/#text-output is it possible to append a bootstrap class to the ui.output_text? I'd like to add `.text-success`

**Comment by cpsievert** [comment]
Yep, you can use the underlying `Tag` method `.add_class()`:

```python
>>> shiny.ui.output_text("foo").add_class("text-success")
<div id="foo" class="shiny-text-output text-success"></div>
```

**Comment by stephenwilliams22** [comment]
This is great. Thanks so much @cpsievert.
