### ISSUE TITLE
ui.output_text color based on render.text value

### ISSUE THREAD

**Issue by stephenwilliams22** [posit-dev/py-shiny#804]
in this simple example I'd like the color of the output text to be `text-danger` if the value of `txt()` is  <40 and `text-success` if the value is >= 40. is this possible? 

```
from shiny import App, render, ui

app_ui = ui.page_fluid(
    ui.input_slider("n", "N", 0, 100, 20),
    ui.output_text("txt").add_class("text-danger"),
)


def server(input, output, session):
    @output
    @render.text
    def txt():
        return f"n*2 is {input.n() * 2}"


app = App(app_ui, server)
```

**Comment by cpsievert** [comment]
Yep, [here you go](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMAgujxM6lACZw6EgK4cAOhFVpUAfSVMAvEyVYoAcziaaAGyXSAFKqYODHDF1QKymlhY6y6dyMr4TIEAcoESAAwSAIwRUUwArBEAlHj2jobE7m4eSv5SLIGpqsmqZRCyNKxyAG5yNq7uEllkORIscCwsHKTJiOkOAAItOQNMg1IVchhKY5WSnTZ9Y45MNVAWerwQORgQS0wAVEwATCuOhBYsW4EsCoSEnYVgvFXrmwB8TAAsEUxwVzgwTA0igEFMdEC5wcUjICjoECcGBYqDBNhogQghxOvGuIHeAF9wkxLlAuppdBiwBQAB5kAC0IEuLCJYFKag5Gi2YlQNg02g47VqcmSYAJAF0gA)

**Comment by stephenwilliams22** [comment]
@cpsievert This worked perfectly. Thanks!
