### ISSUE TITLE
Add Overflow scroll

### ISSUE THREAD

**Issue by stephenwilliams22** [posit-dev/py-shiny#808]
I have a an app that adds a dynamic number of plots that can get pretty large in the horizontal direction. is there a way to add horizontal overflow scrolling to the main panel (similar to https://getbootstrap.com/docs/5.0/utilities/overflow/) when using `ui.layout_sidebar`?

**Comment by cpsievert** [comment]
Yes, you'll get scrolling behavior by opt-ing out of the (default) filling layout, which you can do `ui.layout_sidebar(fillable = False)`.

[For example](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMAgujxM6lACZw6EgK4cJUqITIcAbnAA6EPgKFMIC-jygtjqPQcHCYUMqgA2xMs44AjLNhdumFkwuZHp6aKgA+kpMALxMSlhQAOZwETQczs5Qns5wABR6TEXxHBhZ2MQKZBEsHLKeUHQFEMWtJRi19Y3Nbb3tXKhVNR6yTTqQ4xLjAHKTTAAMEgCM84tMAEzzAJR4hX07e70JlU5DfmQFYKhL4wctfcdVg9Xnl6jrt7v3R6UnzxGvcaoADMn0ObUepxerguQIALGDvm10plsrkYgAxKDOFi6JFbPQEiChCCyGisOTaJoDKoSP60iksWqkLaIcHggAC9JCSI5UlJciwMPBZKCSzyrPBrQgmDoUFJjA6cDg0jySwAnAA2AAc811SyJfSYAA9YkwVvMmABqc0AViYACorBg5QqYC75dIIHk4cCAOyGvrBDCcFgXY0SGlkDDenZMWQQWpkbAxAAqdAUcCJnO5nP5oyFbhFcHJ7wlbKR0tlnsVuJVaq1uv1gd6priFutdsdztd0kVve9voDUuKwdD4cjMqqMYlEgTSZT6cz2d5ud5+cF52LpeB5ZHRRlHrdSvrGp1evmBv3JrNHZtS3tTsPvf7nsH-pbbTHHDDeQjvCnaNYznSgFzTDMsxJVouSeKo8xkTdhSRUVUDhPdK2KZ8a3dOtVTPJtL0-Vo23NVZOwfbssOPAcfQ-a9v1-f8oxnON5w4ZNwOXEkwnQM0xFQPJwiiZQKToKkiTAABfABdIA)

**Comment by stephenwilliams22** [comment]
Thanks @cpsievert but this doesn't seem to give horizontal scrolling, only vertical. Is there a way to get horizontal?

**Comment by cpsievert** [comment]
Oh, sorry for overlooking that! The main panel should be scrollable in the horizontal direction (when content overflows it). [Here's an example](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMAgujxM6lACZw6EgK4cJUqITIcAbnAA6EPgKFMIC-jygtjqPQcHCYUMqgA2xMs44AjLNhdumFkwuZHp6aKgA+kpMALxMSlhQAOZwETQczs5Qns5wABR6TEXxHBhZ2MQKZBEsHLKeUHQFEMWtJRi19Y3Nbb3tXKhVNR6yTTqQ4xLjAHKTTAAMEgCM84tMAEzzAJR4hX07e70JlU5DfmQFYNb4TADudWRsMeObq6gAHuNbh0zfEH+hCCyGisOTaJoDKoSE6DMgSFhwFi1UhbRA-H4AARhVUxUiBciwrhCLWKwKCeVRP1aEEwdCgQMYHTgcGkeSWAE4AGwADnmvKWfz6THesSYK3mTAA1GKAKxMABUVgwdIZMGV9OkEDyABYAMwAdkFfWCGE4LAu7wkkLIGC1OyYsggtTI2BiABU6Ao4ADoOhRWJUHlwlFlKC6OC-mAAL4AXSAA).

(Free free to send a reproducible example with your overflow issue -- it could be something else that's causing it)

**Comment by stephenwilliams22** [comment]
Thanks @cpsievert! The key here was actually setting the width on the output plot container. If you don't do that then the container isn't automatically scrollable
