### ISSUE TITLE
Compatibility of shinylive.io with altair

### ISSUE THREAD

**Issue by stephenwilliams22** [posit-dev/py-shiny#818]
It would be nice if https://shinylive.io/py/editor/ was compatible with altair. Would like to share code and communicate reproducible examples in case of bugs/questions.

**Comment by cpsievert** [comment]
[It is possible to use altair in shinylive](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMASxlWICcyACKAGzKhsbYGc2nADoQAZo2IwWANzgBzKAH0AJlC584ZAXQbMWqriPGSWfABY0I2FjqasAgujwtGcKITI1Zz1xGVxGZwBXGiMJKXNLbAB3GmU5TW16OxZiILJUdMVY+M0fSn9GbLiEshERPjTGQjgWAF59NSgMPjJiQgBrPgAKAEpy6HRFEPqWEKwoBMVRdhDlbpEWJdT0zLJi3LIFojMoZiEwfogjgf9RUwDZRm7LNec0jPTnDT4+GlJexAHllgABB7Wi2Wv18hQ2pSBSzOLEIu2YfS+EB+P1he1YDQ4ZAwAGE4VtKkFqnBehgyIwoBA+KImDBpjROAEFkjkSyAOQGIIwFrYGAAI2I7DqQoOAHEAPJikUHVmQ5EkmB7DqKPZuJkslltAWeVB1AAqjCCcDwsvVLHYljgdRArJI7CYrMQLFZAGIAAwAJgAHABGbEAEVZAF9jczTUtbUw6piMCLycoaJQtiaw0s5HGE+Q6qzzRA3IxWSGUyzWsRUHw6sBo7GoPHEwBlNqoboRxhZ6IWCgF1KiUQaMh1V29QtFotV9P1xvNgWRl0en3+rvEHt9ure3oAXWHI6WAA9vavnDv3QeWNh997nNhj67kyyjqaSZQSP41aPOBgABrddlqOCIXWskOt7ItGACa36oIwNA1IgACKgHASSkGlgEnhwD0wE-J4ZDsJaIAHBQO5lEgLDAKKxDEHIuGsgIJadCwkHQbUxBXCwnjwAc66Boh3zqq4ZCEki0YAFJBDgFCMLiaLNni97LAMaCoKMjhNopww0M8lwBEcYDBuA0DwNQrgAI4hK48DkHwpJEfgRCkBQVDIBSMQlJoIiYtwjAiLICgqE0fZ8CIunrkAA), but for now, you'll need to explicitly pass a `alt.JupyterChart()` to `render_widget()`/`register_widget()`. 

Once shinylive updates to the latest shinywidgets, that should no longer be necessary (shinywidgets will automatically coerce `alt.Chart` to `alt.JupyterChart`).
