### ISSUE TITLE
Update examples to use lowercase `reactive.{Calc,Effect,Value}`

### ISSUE THREAD

**Issue by schloerke** [posit-dev/py-shiny#823]
From #822 
> This PR changes those names to lowercase, and adds aliases so that the old capitalized names still work.
> 
> This PR does not change any examples because if users on a previous version of shiny were to use the example code, it wouldn't work for them, and it would be unclear to them why. In a future release, we should update the examples to use the new lowercase names.

**Comment by wch** [comment]
Note that we also need to update the examples in the shinylive repo and py-shiny-site.
