### ISSUE TITLE
Async reactive functions run sequentially instead of concurrently

### ISSUE THREAD

**Issue by wch** [posit-dev/py-shiny#837]
In previous versions of Shiny, it did the following for async reactive functions:

- Within a session, async reactive functions _within_ ran sequentially. This was done to prevent a reactive flush from being run while another flush is happening.
- Across sessions, async functions ran concurrently. We decided this was safe, as long as there were no top-level async reactives which caused a flush in the middle of another flush.

It turns out that, as of now, both of these situations run async reactives sequentially. This is safe, but it also eliminates the performance benefits from async code.

This is a test app that demonstrates the issue. If you run the app and visit it with two browsers, and click on the button in each, you can see that the async `render.text`s run sequentially instead of concurrently.

```py
import asyncio
from shiny import App, Inputs, Outputs, Session, reactive, render, ui

app_ui = ui.page_fluid(
    ui.output_text("id"),
    ui.input_action_button("button", "Compute"),
    ui.output_text("compute1"),
)

def server(input: Inputs, output: Outputs, session: Session):
    # Get first 5 characters from Session
    id_num = session.id[:5]

    @render.text
    def id():
        return f"This session has ID: {id_num}"

    @render.text
    @reactive.event(input.button)
    async def compute1():
        for _ in range(8):
            print(f"... computing for ID {id_num}")
            await asyncio.sleep(0.5)
        return f"Finished run {input.button()} for ID {id_num}"

app = App(app_ui, server)
```

https://github.com/posit-dev/py-shiny/assets/86978/2eb987b7-3c0f-4df0-9f2c-a456332d2a9a

However, if we go into `shiny/session/_session.py` and comment out the following `async with lock`, then the two can run concurrently:
https://github.com/posit-dev/py-shiny/blob/351598bc41b1eec3d2068b7f75ec874b76eca498/shiny/session/_session.py#L272

https://github.com/posit-dev/py-shiny/assets/86978/c389da5f-7372-4d6d-b201-78b8187552cc

That `async with lock` was added in [4a0e5bff](https://github.com/posit-dev/py-shiny/commit/4a0e5bff7ff4a9eacffe5fcb8448d1265782b8fa#diff-593b4caeaea701b19634390e87e303e7003164d20d3afa0f773e085f3e0d39d1R195).

**Comment by wch** [comment]
One comment about using `async` in a Shiny app. Currently, if you have a reactive output/calc/effect with `async def`, it will not run concurrently with other `async` reactive functions, even across sessions. This is a bug. However, this still can be useful, because it makes it possible to call `async` functions.

We are currently working on making it possible to call async functions concurrently, even within a single session, but the shape of the API will be a bit different than simply using an `async` function.

**Comment by adampinky85** [comment]
Hi @wch, thanks for your efforts on this issue! Do you have an estimate for how long the async fix will take to be released? 

The full solution with async even within a single session will be great. But the blocker for our team to roll py-shiny into production is the sequential behaviour between users.  The sequential behaviour within a single session is not a major concern.

Shiny is such a great product, we've been using r-shiny for many years, and we would really appreciate being able to expand into py-shiny. Many thanks!

**Comment by wch** [comment]
@adampinky85 We have a pull request for  (#907), and we are hoping to have it merged for the next release, which will happen some time next week.

Here is a [live example app](https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMASxlWICcyACKAZ2wkJuIB0IAM0bEYLACZQKZOnBZ0GzCVLgz4AgcNFtO3APoALOABtUcRu3n0mrdseIB3PSXoBXMlN4QNQkWPYGNBDYVoqsjHBQhDIAbnB4LBEQ4uYJrjSafiwBQdgYcAAeqBHslgo28hCo7gnGUNjENdmu7GbJeuI0rXXYPg40ZAYsPY1kGOw0KQBGUIwAFDBQBYZwNADmBmR6MMRTNMZwALx8KO78YACUiAIstyzpGEHVWxCu8Iw0hHMnBScJP38WAAmAAMFxudweT3cele70+3zAvXwLBOyISAGYwRDblCqjCojJSHopu4yKREVMyBAAIyAk4AYVEzzkNISdkcxnRLEIdVKemOYCpEAAtOxXIRCHBSidwRA7vcaI98VtCV4SWSKSdhUD6WAmW4KMD2fYHFzAbyOOwBdrqWKJVKZZcfA8DABWREM1yMJKsNRwWU+AQAASSKUYGAoBTIAhSgh53t9en9cyuOMSkWiNDiypiUGMkxUejqFHmNLlCoiZG98sk0lkGAgjlT4zIjEEKZOAFIABKILsAWX7AGVA95x675nKfMGOU4XM9PKQBBwuIQJHB43PnMz3HAaXMoIhKmQElNj0EyBcWCKAHwn67yu6CJjySqJKAQNZwOYADjTT4KrcxSXnMgiMruMhfiwNLHiAUAAL4sAA1CwIBTAhJwoaiYAYFhABU8gVkBtxQA4UADDoa68OMBxwKgcwghgbrEbcVY1mw2FTEGECzqaO6Gku46rtwG5bvxC57kCh4XuQZ6yVeN73pej4Ki+jBvkEH5fj+-6qSRLAgeQYEQYaQRrMCcGIdh6GYWA2EnHh9mETQrFAWRFGsCJPDELRcD0YxzFuexjDylAXE8aGmaxHAGAAKKCIIcDRCGERqjmcBxMZ0JjMK5axpuLAGJ+4gHM4BaEAA1geAEKtukkUDSubEJVP45RgBSpgk7XYKm07jlF6WxQlSUpbxaVZhlWVkHM7U6nKcZFSVZW8p8lXSbVdz1ZBcBAs1rWzSqHVdZUzwYL1Fz9QIroeoyiaULYHjVpYdLOuOqWUOGkaFDGySFQEjh6OwT0tDV+lsaoHHbYa+6tlILSpjxN2IgAStKrjGKwxDxg1QkwWOM5huY33RgVW4GIDJQY2QYPpiF8rA-M0Msk1VOY31SNKgYU7XVzt36vd5DZCDli6m9hOfcTUa-YtANOMD8PsBt4MZtWoXZBJO17Qrz2I+9rx86j6OYyw2M8pBeNi1d42SxG0tk9kFNOGzZDK3TkPq4zczM1JGAuxzEBgAheDgNA8DUN5KymOY7BYLgBAkOQD3UAAxIZ2AfBsZDHozny-QI5RKN5vCZNoZDYKg5mhBU3yASwACC5EDFAUwHHg6YMvmdSt-E6YAOKUOYnzt3XAAyAzmPmI8KgA8qgRLQMY093AACrMsDDmYhDL7cAAqFdwAAarMO88hwp7psQcSMPYUDiCP-VaP4gTBNXSgTTFCQRAAjuy0oTMuccK8WCHBYGvRgG8t6IhXmOFGICWD7zMMfeYJwUYEwgMOEW8Dx6lnzMAE4QQBg0HzHqRgrgIAQHMnqcUkp-56nMCIRgepCCfilMYA44gTgAF0eKWlKCwAAIpQYhxgmRJ2jHMD+2ZYo7giBgMR0tNq3BOCosA6Z67m3EX6YqrAUiUOlGwdhGZv6uGlGQSw5IMx3ysZNOQ7BGiMEdBgFgAB1OQLQ5CDC6CwSxlBxQRHTIMKQ5sUiJHIabdwExQlmykTmewVUJDEGlBAAA5KwIId9r4UFKiENK4gbExWyA4px6ZVEqPHAqRaxIgh5gLHWH87ATCCASIIchhBjyd3YS3A4wBgBcISAAOVIHALh147wsCGRAOAKtKwUUaSwFG5D-RxR9EwWuBkgInAAJqNBSREFgTYvLsMcHAfJli8kFOkUU70joWBP0qFEuQ4VhymgNIuBe5SNnWz4ZYF5jg3nuCEnMAeUyPiEGACvBIKNRkqzTrvGeAiZ7HhcTonxxBEksAcEYeUehnBd1xfISwLD2GnMxYEA4nFiiZV4C0c2gkF6EuFvsYw6Y05kIoeZAA-CwYcFMMb5IcHIFh3ATA+KMIZCIMQaWWGGdy3ljRjACrkCYuApj7ioDFXIKZDhTZTLlXyxVrLMWeO5o4Ng8oGFME5T4SphVcWEK2Hob2TSWltI6V3bpcAIUJEbp5T1wBoUwvTHVJpGBWmiVAeGwgwatqho8OwSqx454LzwcXXyu8OCVQDVwrh8DJkBgqQZNODqv7kMoV+dkDp-4JEtUwuuIbjCCDhs9Y8sTYrH2MKY4AmDFa5tAW2jAHbTGIgdSIscGzGmNowLU0xrborSMHfmLt0L4EDqHT+NyDam21rnUNRdnavUACEOBwDigUKU88vB9suTmddesY23DTgASXjDUlqpKsX7CeRK6ljQygQBiMQFhDLvHA2ZWEjlFbjUsBVWq1wmAH3ZFDXoN9wH1SwemcMLoZBgCdO7j0vpgzhk5vgX0m1dxFrCrYc6xtYz7z5pmXcMpaj613E7iK4wmqEw+gepUQDaHSDdXjJ+PILAX2av2bMOQ7Ly0WVQ0JdgCQqMmEQ4MYg8zyS+UQ8xxDk6m0oYA0BoSegMMYF5JEHmrHbg0C3HGzNjLDkTOGYxkienIyZrM6wkw9666LTfQdPTCR8KzDWOwY8K8MAhcUywfC+FKrkUYKF8LGB4tRbo05qZLmcJlKswsuAKrgYsEKMldwXhTbxkGHY00dL3leGceJyrEQUmWHzHkkI4VcYgcLSRYoxA1glGi14yw-QjEYfVVx7VfGjMMssVMaT4SoAdnMFxwggssZTLwrl3e4qQtvAehY9FQ27ltIZVJwyVpSWWMq-cP6N9sBVyjQvTbiG0ZqwgOwRDIovvfZFIhrLCon0wHgJ0FQXJVY1ksAAA3zZD5x23pPG3MeVlbFsGUjc43NtgeZ9iesQwqKV4VruQ-9hcSHLB4BqfEJtjZOncv9EGDe2KXRiAlg3f9u4NmkNTp1gja8hxQEnBk1Q+yr4DgQBo-p+TC8TOmNMdee8IJ2eueQ1L9DsvYpoDaOIOYdQYBTEkDnFXhmDrBcS9F2LqWzeXTx3cEwjSldATcwZwDJuotBbiwl0L-VbXxmd++iXQWovJbdzFj3QewEpc9+wdLDHtNqPj4hp9SdQr5lCAceA5A8Zm0h-5jdsOEHiuqK3T4mKIHoGW71ig0QLGBEsBTimnDcv3Lm1XYlHCyVfspZK6VU2BPylAzIIxQuvzU4MrTjZF2lBufjZVRl+byPK+5yLcYqhETD7WOOgybmZ2xXIY0mam7Y1TtrRgPfq-D+3Gn-Z0BaazNpQoMmTNEuMB6GK6t6XDgy9mHmKb0L7vLde4X5c5Noz6RbiDiAdDDJ4rsIzBVTP6QFTLQHGCwGVTe53DeRiQsCv4FAlYf5f7mAB4xbh4RYh4W5R7JYAHR5KQLJZbj4GQuJl417uKNIaQkChJaQdakDSxirBJ6I0AGJRCOgHaM7XKOLSij4kR0EkT05DADqyIyJtqv4AY0AiAQAZ5jAeI7haJzBCKUL5gKI-R9QO70xsBNy2ChpRpzC-7m5h5W4L6YEIFwBIEoGEEz7Hi34ZoJrZox7OZx45YbLDiZSTycZeJfh14tCsDFTl7yhYqUCcQz53KEIBDShZZNQsAACqqA9SXGPOLWyQLAO+AA9CfohntHlkNHcp2gEOyIdqim2huFrpQDwAYsKuTlfHIOpAllTohhiPVhVkYJJvshhvkvBr3gpqWvKNdlMtGLqrFH4Qnt1kBJzlfgmg5sQH6JmsYR7E+HCrXj4vZuRESl5iSvfOavkuFJNsMpihwMLLMNkvYQqM+v0Z4vZoIBRBwuyFAHEFxrWu+G5iUblk8fILYFWqcqcp8d8ddi7H8aGjvhIY7nZqsaAvPosQqBgYtChvQMYKmA7hgTIYzhgPEpVDiTbiRJzqAcpicSSblhslus2i0CvjNCcJSRwpvrSUBCYOSR5oUBegvKmGsawLHjSeycAfkKshGPvnMCwsDHMMeo0meryV4AkKATyfRHyZdEASKaKbkYyYiLWmyVqUVsYPbqSbSdvkurFJKaASTpqSKW5jqZKScDQkIegoaegWYQSYIFUQYD5m6dZvGGLvAarsSBhvLiwIrqaRstMVsMGfKKAk7rGTLqqrFAwAxNiMKeydGX7n3nrH6e5B6QOl6S0D6WgSRLfoQPfk4TPnMJiagNidbosYtP7HpulijFlssaGrkfyfzjhM6XQkgKaSYeaQehgN+AfohpybZkvorN2QLmAPqQORmR+F0HYqGifmObmQZHbphiwMWpQqeBBrJkpscayUuXCgikimJqwA4AqvkpjmlOwiEJQlKPIPGIKubPyuTlAK1CtmthEmQM8CwLNMJsELaY+iwJjn7MlPmKtiWA9lkE2DqksvsCjvSmVoIEkUYLHIOflnMAAGL5iNLWzBjtE3zEB3wOw+xPReD8njJ4b+q4Yeo9zeoNxmH+qBr9I8qvKo5eAsWBoqwYCCWRSkW3yN6yyaxoUUhRrupdLMWQqsV+rMWBrpZ-IOAArUWkB8VcICVCX6ziWAydY0XpjSUsDJpeB4L0VyU+psVKU5rXoonpbrJ3CqXqVCRaUsAAA+LAllBGPlXq8lvqzctlOaCQLlPFml8lgaAgSi2WCxCoQiJAEC5IGkliiwjAs+n4VEokj2ZWNx4Uc4NWgKT2Be3i6OZ8HimqxlJ2ZWs282-eYUEFUQlU-WjQ+RM+CQJUXGLsw24GmOXx7xnqBRxClVdckOYVklEAZOuwAAVslOENsaSlMCENdikIlVIEwM9nXOkRAAWD+U2IwIsJxhgUTBpDlaQNFpuKNOYh1fkcSoQNFpDlRUJGTt5OmIZedRio5q3EBrPtdosFpIMHknDnsfAJ+DXsEpViEK0Zjh4mcvwHXN-upGIPYF+CKOvvsQmj1Wpu4BBUSVXNdukU+ptQqD2CctfMqXsYReiqDe9jwdonAFDZ+I5oIf-CIfYjcuISVWUJYHNiwh4oEuKv9ZMdzJEPkt4l9USeCWcUUl1fOt8ezWIXXvUDyMVDpB3hSpVm9eFf3pYOvn0earknLXYsUgIfslMmCXecteKu9RABTQzemDABERBXIKgBdmLWFC1olntuQMIddmdRAMTavOvBTjHOmD9uHb9nXFGiwDJfhl6hCpxYFR4MFYhvDsdtwDNuiqtUwCoPVqwK0R4D+SJudhAiHRYNLSYcXTvohodLyK4J0NBPmhcIHbcK9hDmHRHemFlhomNdxRNVNVMLNdEHTWfPKDDY0nDSrclL9eKrkcjprbljbRXaoB8EEbLeKJjPCbTumItNnUlWsiZX5SxUnexTmipX3bVhFVCtpYhiYeNZfeLlGqWa+eneuOLesRltMrfdsRuGtclWBG0m5NuVliYXvetXWkHFwkAA) that demonstrates an early version of the code that's going into that PR.

The code change doesn't make cross-session concurrency automatically happen -- instead, you will have to be a bit more explicit about setting up concurrency with async functions. Basically, you have synchronous code start a new `Task` (which can run concurrently with any other Shiny code), and then when the `Task` finishes, it assigns the result into a `reactive.Value` object, which triggers a flush of the reactive graph.

There are two benefits of this:
- You can have async functions running concurrently within a single session.
- It avoids a potential problem in the previous cross-session concurrency code, where if a reactive object was shared across sessions, one session could trigger a reactive flush in the other session, in the middle of another reactive flush. When this happens, it would cause problems, but the situation would also be rare and very hard to diagnose.

The API and user interface is going to be really nice, so stay tuned!

**Comment by adampinky85** [comment]
thank you @wch! the api looks great, can't wait to try this out :)

**Comment by wch** [comment]
@adampinky85 We decided to hold off on merging #907 for this release, but it will go into the next release, which should be in about a month.
