### ISSUE TITLE
shiny create fails to create Dashboard

### ISSUE THREAD

**Issue by karangattu** [posit-dev/py-shiny#844]
When trying to use `shiny create` to create a dashboard, it runs into an error
<img width="848" alt="README_md_—_py-shiny" src="https://github.com/posit-dev/py-shiny/assets/4220325/f3a4f190-d28b-4bdc-8998-f1ce74951b15">

Even after running the command `rm -rf __pycache__` it still throws that error

**Comment by gshotwell** [comment]
Is this from `pip install -e` your local version of pyshiny? I think what happened here is that you may have run the Shiny app in `shiny/template/app-templates/dashboard` which created a (git ignored) pycache directory. Can you check? I don't think that that file got checked into github. https://github.com/posit-dev/py-shiny/tree/main/shiny/templates/app-templates/dashboard

**Comment by karangattu** [comment]
yeah I might have ran `pip install -e ".[dev,test]"`
Let me try it with the `pypi` shiny

**Comment by karangattu** [comment]
ok after running
```shell
➜  py-shiny git:(main) find . -name "__pycache__"
./basic-app/__pycache__
./tests/pytest/__pycache__
./tests/__pycache__
./dashboard/__pycache__
./examples/typed_inputs/__pycache__
./examples/inputs-update/__pycache__
./examples/dataframe/__pycache__
./examples/penguins/__pycache__
./examples/express/__pycache__
./examples/global_pyplot/__pycache__
./examples/load_balance/__pycache__
./examples/airmass/__pycache__
./examples/moduleapp/__pycache__
./examples/req/__pycache__
./examples/headers/__pycache__
./examples/duckdb/__pycache__
./examples/cpuinfo/__pycache__
./examples/static_plots/__pycache__
./examples/brownian/__pycache__
./examples/brownian/shinymediapipe/__pycache__
./examples/model-score/__pycache__
./examples/event/__pycache__
./examples/ui-func/__pycache__
./examples/annotation-export/__pycache__
```
after removing those, the creation works as expected

**Comment by karangattu** [comment]
ran this to clear all the `__pycache__`
```shell
find . | grep -E "(__pycache__|\.pyc|\.pyo$)" | xargs rm -rf
```
