### ISSUE TITLE
Consider making `page_fillable()` the default for `shiny.express`

### ISSUE THREAD

**Issue by cpsievert** [posit-dev/py-shiny#846]
This way, top-level fill items like plots, cards, or widgets, will fill the page how you might expect them to, for example:

```python
from shiny import render, ui
from shiny.express import input, layout

# This could go away
# layout.set_page(layout.page_fillable())

@render.plot
def hist():
    import matplotlib.pyplot as plt
    import seaborn as sns
    df = sns.load_dataset("penguins")
    fig, ax = plt.subplots()
    sns.histplot(df, x="bill_length_mm", hue="species", ax=ax)
    return fig
```

Another benefit of doing this is that we might not have to change the page layout for a top-level `with layout.sidebar():`

<img width="860" alt="Screenshot 2023-12-05 at 3 35 26 PM" src="https://github.com/posit-dev/py-shiny/assets/1365941/e0e4b941-acd9-4d1c-b635-cc7abf390ea6">

BTW, @wch, the last line in that screenshot should be `layout.set_page(layout.page_fixed())`

**Comment by gshotwell** [comment]
I don't like having to call both `layout.sidebar()` and `sidebar` to get a sidebar layout. The most familiar interface for people is probably the Streamlit one which uses the context manager to just set the sidebar elements:

```
st.subheader("header 1")

with st.sidebar:
    sample_ui = st.number_input(
        "sample", 0.0, 1.0, value=0.1, step=0.01, on_change=increment_counter
    )
    log = st.checkbox("Log Scale")

st.subheader("header 2")
```
So I think the current implementation is probably closer to what people are expecting:
```
ui.h2("header 1")

with layout.sidebar():
    ui.input_numeric("n", "N")
    ui.input_checkbox("check", "Checkbox")

ui.h2("header 2")
```
