### ISSUE TITLE
Add the equivalent of `bslib::layout_columns()`

### ISSUE THREAD

**Issue by cpsievert** [posit-dev/py-shiny#855]
Fairly recently, `{bslib}` gained `layout_columns()`, which is now our recommended starting point for column-wise layout. 

https://rstudio.github.io/bslib/reference/index.html#multiple-columns

It also supersedes the the `row()`/`column()` interface (it supports filling layouts, wrapping onto new rows, etc), so when this gets added we should also drop `row()`/`column()` from express.

**Comment by cpsievert** [comment]
Once this gets added, I think there is a strong argument for removing `layout_column_wrap()`, `row()`, and `column()` from `shiny.express.layout` (and promoting this function as the layout "work-horse")

**Comment by gadenbuie** [comment]
Another option discussed today:

* `layout_columns()` for `bslib::layout_columns()`
	* Reason: it's a workhorse function that covers most of your column-layout needs)
* `layout_columns_grid()` for `layout_column_wrap()`
	* Reason: the result is a grid, i.e. a literal grid and not just a CSS grid, a.k.a. what most people think of when they think of "grid".
