### ISSUE TITLE
Add a helper for setting page arguments

### ISSUE THREAD

**Issue by cpsievert** [posit-dev/py-shiny#866]
As highlighted in #852, this unfortunate code is required to get a page title with the sidebar layout.

```python
from shiny.express import layout

layout.set_page(layout.page_sidebar(title="Page title"))
```

And we have a similar problem if you want to change page-level settings like `gap`, `padding`, `lang`, etc.

I think it could make sense to have both a `.set_title()` and a lower-level `.set_page_parameters()`

**Comment by wch** [comment]
Some options and comments:

1. `layout.set_page_sidebar(title="Page title")`: One would never actually use `with layout.page_sidebar(title="Page title")`, so it might make sense to get rid of that function and replace it with `layout.set_page_sidebar(title="Page title")` (and same for the other page functions). Drawbacks: the user still needs to know what kind of page function is used by default.
2. `layout.set_title("Page title")`: This is nice and simple, but doesn't really make sense to extend to all the arguments for `page_xx` functions.
3. `layout.set_page_parameters(title="Page title")`: This is more general than `.set_title()`, but we can't offer the user much support for knowing what parameters are available. So in the end, other than very common parameters like `title`,  the user still would need to know which `page_xx` function they are using, and look up the available parameters there.

To me, there's not an obvious winner here.

**Comment by cpsievert** [comment]
We now have `shiny.express.ui.page_opts()` which gets at the main idea here
