### ISSUE TITLE
Unhelpful express error message: `Error loading ASGI app. Attribute not found in module "shiny.express.app"`

### ISSUE THREAD

**Issue by cpsievert** [posit-dev/py-shiny#869]
At least one way to repro this is to run an app that attempts to import something that doesn't exist in `shiny.express.layout`

```python
from shiny.express import layout

print(layout.foo)
```

**Comment by wch** [comment]
This is the error message:
```
ERROR:    Error loading ASGI app. Attribute "_2f_Users_2f_winston_2f_Projects_2f_py_2d_shiny_2f_examples_2f_express_2f_plot_5f_app_2e_py" not found in module "shiny.express.app".
```

Interestingly, I found that this happens only if an `AttributeError` is raised, as in:

```py
from shiny import express

raise AttributeError("This is an error")
```

For other types of errors, like `ValueError("This is an error")`, you get a normal stack trace, like:

```
Traceback (most recent call last):
...
...
  File "/Users/winston/Projects/py-shiny/shiny/express/_run.py", line 44, in wrap_express_app
    app_ui = run_express(file)
             ^^^^^^^^^^^^^^^^^
  File "/Users/winston/Projects/py-shiny/shiny/express/_run.py", line 96, in run_express
    exec(
  File "/Users/winston/Projects/py-shiny/examples/express/plot_app.py", line 17, in <module>
    raise ValueError("This is an error")
ValueError: This is an error
```

In Shiny, we're not doing any special handling of `AttributeError`, so I think uvicorn is probably catching that specific kind of error and handling it differently.

**Comment by wch** [comment]
This is where uvicorn is catching it:

https://github.com/encode/uvicorn/blob/c55af77fe9a4da99ac594e15ab9ee07b34ef669c/uvicorn/importer.py#L29-L36


```py
    try:
        for attr_str in attrs_str.split("."):
            instance = getattr(instance, attr_str)
    except AttributeError:
        message = 'Attribute "{attrs_str}" not found in module "{module_str}".'
        raise ImportFromStringError(
            message.format(attrs_str=attrs_str, module_str=module_str)
        )
```

I think the best course of action is to catch that kind of error and raise a different one that uvicorn won't catch.
