### ISSUE TITLE
Consider switching default Express page type from `page_fillable` back to `page_fluid`

### ISSUE THREAD

**Issue by wch** [posit-dev/py-shiny#886]
This came up in a conversation with @jcheng5: I merged #850, which changed the default from `page_fluid` to `page_fillable`, but there was a drawback to `page_fillable` that didn't occur to me: if there are many plots or cards on a page, they might get compressed so much that they look bad, or, for plots, so that they don't work at all. The same can happen if there's a fill item (plots, cards, etc) along with content that doesn't automatically resize.

Here's a screenshot of what can happen:

<img width="1384" alt="image" src="https://github.com/posit-dev/py-shiny/assets/86978/a377c580-153d-4b69-b97a-9819325225cb">

**Comment by gshotwell** [comment]
We should probably do this and then maybe implement some vertical scrolling layout (page article or whatever) for express. Is it possible to make `page_fillable` only fill horizontally? That might work.

**Comment by jcheng5** [comment]
I think @cpsievert and I were thinking `page_fixed` instead (and I might argue for a narrower variant of `page_fixed`, the bootstrap version is so wide that it is all but indistinguishable from `page_fluid` most of the time IMHO)

**Comment by wch** [comment]
I'm fine with `page_fixed`.
