### ISSUE TITLE
dynamically generate text output

### ISSUE THREAD

**Issue by ME-researchgroup** [posit-dev/py-shiny#915]
Hi! 

My app performs a long running process when an action button is clicked and I was wondering if it is at all possible to render log messages in a output_text or output_text_verbatim ui while the process is running. Is this something that shiny would consider implementing or is there currently a way to accomplish something like this? 

```python
def long_process():
    sleep(10)


app_ui = ui.page_fluid(
    ui.input_action_button("run_process", label="Run"),
    ui.output_text_verbatim("log_msg"),
)


def server(input, output, session):
    @output
    @render.text
    @reactive.event(input.run_process)
    def log_msg():
        yield "Running a long process... "
        long_process()
        yield "Success!"
```

**Comment by wch** [comment]
https://github.com/posit-dev/py-shiny/issues/837#issuecomment-1855212425 and #907 might be helpful for you.
