### ISSUE TITLE
For `page_sidebar` and `page_navbar`, consider changing default for `fillable` to `False`

### ISSUE THREAD

**Issue by wch** [posit-dev/py-shiny#938]
For Express mode we had set the default page type to `page_fillable()`, but changed it back to `page_fixed()` for reasons explained in #886.

In Express mode, when a sidebar is added, it uses `page_sidebar()`, which defaults to `fillable=True` and then runs into the same problem. That means that from the user's perspective, simply adding a sidebar makes a big change in how the main content of the page is laid out, and can lead to surprising errors. For example:

<img width="1326" alt="image" src="https://github.com/posit-dev/py-shiny/assets/86978/c5ea3e03-2ac3-4eaf-9d21-551aef725012">

Then the user needs to know to use `ui.page_opts(fillable=False)` to fix it.

Especially in cases where there is a lot of content on the page, I think it would be very surprising for a user that simply adding a sidebar would result in this change; and then in order to understand the fix, they would need to understand the fillable concept, and that the sidebar changes the default behavior of it.

**Comment by jcheng5** [comment]
I'm inclined to agree, though I think we should discuss in person with @cpsievert and @gadenbuie as I know they put a lot of thought into it.

**Comment by wch** [comment]
FWIW, I ran into this while working on example apps for the docs, so I don't think it would be an unusual problem to users to encounter.

**Comment by cpsievert** [comment]
I can get on board with `fillable=False` for `page_sidebar()` -- for consistency, we'll also want that for `page_navbar()` (and possibly doing the same for bslib?).
