### ISSUE TITLE
`shiny.express.ui.card` doesn't render card items properly

### ISSUE THREAD

**Issue by cpsievert** [posit-dev/py-shiny#948]
For example:

```python
from shiny.express import ui

with ui.card():
    ui.card_header("Header")
    "Body"
```

<img width="444" alt="Screenshot 2023-12-28 at 3 22 47 PM" src="https://github.com/posit-dev/py-shiny/assets/1365941/059e6ce1-fac5-42a0-a782-7db14932739e">

Both the header and the body are being wrapped in a `.card-body`, which is leading to the extra, unwanted, padding.

**Comment by wch** [comment]
For reference, this is what it's supposed to look like (with the DOM structure below):

<img width="530" alt="image" src="https://github.com/posit-dev/py-shiny/assets/86978/e6e0b12c-be43-414c-9f54-d1a3f8e0c13a">

*****

And this is what it looks like on `main`:

<img width="530" alt="image" src="https://github.com/posit-dev/py-shiny/assets/86978/33767fc8-4220-4d9a-abc9-c1fd4449cd3d">
