### ISSUE TITLE
Shiny create: Basic App creation overrides files.

### ISSUE THREAD

**Issue by dfalty** [posit-dev/py-shiny#958]
When creating a `Basic App` in the directory with another shiny app, the files get overridden. When creating a `Dashboard` or something else, I get the proper error message. `Error: Can't create new files because the following files already exist in the destination directory:`

Steps:
1. `shiny create`
2. Select `Basic App`
3. Select `Yes` for Shiny Express
4. pick a destination directory
5. Edit the app.py file that is created
6. `shiny create` again
7. Select `Basic App`
8. Select `Yes` for Shiny Express
9. pick the same destination directory as # 4
10. See the edits for app.py were overridden

**Comment by gshotwell** [comment]
I can't reproduce this, can you provide more information about your setup?

**Comment by dfalty** [comment]
Sure thing! Let me know what specific info you need if it isn't this.

OS: macOS 14.2
shiny: 0.6.1.1
Python: 3.9.6

Here is the output of me reproducing it again.
```
darbyhadley@darbyhadley-TX4L ~ % shiny create
? Which template would you like to use?: Basic App
? Would you like to use Shiny Express? Yes
? Enter destination directory: ./1/testshiny2/
Created Shiny app at 1/testshiny2
Next steps open and edit the app file: 1/testshiny2/app.py
darbyhadley@darbyhadley-TX4L ~ % shiny create
? Which template would you like to use?: Basic App
? Would you like to use Shiny Express? Yes
? Enter destination directory: ./1/testshiny2/
Created Shiny app at 1/testshiny2
Next steps open and edit the app file: 1/testshiny2/app.py
```

If I create a Dashboard twice, it errors as expected.
```
darbyhadley@darbyhadley-TX4L ~ % shiny create
? Which template would you like to use?: Dashboard
? Enter destination directory: ./1/testshiny2/
Created Shiny app at 1/testshiny2
Next steps open and edit the app file: 1/testshiny2/app.py
darbyhadley@darbyhadley-TX4L ~ % shiny create
? Which template would you like to use?: Dashboard
? Enter destination directory: ./1/testshiny2/
Error: Can't create new files because the following files already exist in the destination directory: "requirements.txt", "README.md", "penguins.csv"
```

**Comment by gshotwell** [comment]
Okay I can replicate, here's what's going on for posterity:

- We were inadvertently checking if any file or directory existed in the destination directory which also existed in the template directory. This included the `__pycache__` folder
- When we copy over `app-core.py` we change the name to `app.py` which means that it wouldn't trigger the error (app-core.py is not the same as app.py)
- Previous testers all had the `__pycache__` folder so they weren't seeing the overwrite, but that's not a stable or informative test

I changed the code to ignore `__pycache__` and always error if there's an `app.py` in the destination directory. 

Thanks for the excellent bug!
